/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  account: {
    api: {
      Account: () => import('#transport/account/controllers/api/account_controller'),
      Preferences: () => import('#transport/account/controllers/api/preferences_controller'),
      Profile: () => import('#transport/account/controllers/api/profile_controller'),
    },
    front: {
      Account: () => import('#transport/account/controllers/front/account_controller'),
      EmailChange: () => import('#transport/account/controllers/front/email_change_controller'),
      Preferences: () => import('#transport/account/controllers/front/preferences_controller'),
      Profile: () => import('#transport/account/controllers/front/profile_controller'),
    },
  },
  auth: {
    api: {
      AcceptInvitation: () => import('#transport/auth/controllers/api/accept_invitation_controller'),
      EmailVerification: () => import('#transport/auth/controllers/api/email_verification_controller'),
      ForgotPassword: () => import('#transport/auth/controllers/api/forgot_password_controller'),
      Login: () => import('#transport/auth/controllers/api/login_controller'),
      Logout: () => import('#transport/auth/controllers/api/logout_controller'),
      Me: () => import('#transport/auth/controllers/api/me_controller'),
      Register: () => import('#transport/auth/controllers/api/register_controller'),
      ResetPassword: () => import('#transport/auth/controllers/api/reset_password_controller'),
      SocialApi: () => import('#transport/auth/controllers/api/social_api_controller'),
    },
    front: {
      AcceptInvitation: () => import('#transport/auth/controllers/front/accept_invitation_controller'),
      EmailVerification: () => import('#transport/auth/controllers/front/email_verification_controller'),
      ForgotPassword: () => import('#transport/auth/controllers/front/forgot_password_controller'),
      Register: () => import('#transport/auth/controllers/front/register_controller'),
      ResetPassword: () => import('#transport/auth/controllers/front/reset_password_controller'),
      Session: () => import('#transport/auth/controllers/front/session_controller'),
      Social: () => import('#transport/auth/controllers/front/social_controller'),
      TwoFactor: () => import('#transport/auth/controllers/front/two_factor_controller'),
    },
  },
  cms: {
    admin: {
      PageRevisions: () => import('#transport/cms/controllers/admin/page_revisions_controller'),
      PageTranslations: () => import('#transport/cms/controllers/admin/page_translations_controller'),
      Pages: () => import('#transport/cms/controllers/admin/pages_controller'),
      PagesCreate: () => import('#transport/cms/controllers/admin/pages_create_controller'),
      PagesPreview: () => import('#transport/cms/controllers/admin/pages_preview_controller'),
      PagesShow: () => import('#transport/cms/controllers/admin/pages_show_controller'),
      PagesUpdate: () => import('#transport/cms/controllers/admin/pages_update_controller'),
      Templates: () => import('#transport/cms/controllers/admin/templates_controller'),
      TemplatesPreview: () => import('#transport/cms/controllers/admin/templates_preview_controller'),
    },
    api: {
      BuilderOperations: () => import('#transport/cms/controllers/api/builder_operations_controller'),
      PageRevisionsApi: () => import('#transport/cms/controllers/api/page_revisions_api_controller'),
      PageTranslationsApi: () => import('#transport/cms/controllers/api/page_translations_api_controller'),
      PagesApi: () => import('#transport/cms/controllers/api/pages_api_controller'),
      PagesCreateApi: () => import('#transport/cms/controllers/api/pages_create_api_controller'),
      PagesDeleteApi: () => import('#transport/cms/controllers/api/pages_delete_api_controller'),
      PagesPreviewToken: () => import('#transport/cms/controllers/api/pages_preview_token_controller'),
      PagesShowApi: () => import('#transport/cms/controllers/api/pages_show_api_controller'),
      PagesUpdateApi: () => import('#transport/cms/controllers/api/pages_update_api_controller'),
      Templates: () => import('#transport/cms/controllers/api/templates_controller'),
      TemplatesPreviewToken: () => import('#transport/cms/controllers/api/templates_preview_token_controller'),
    },
    front: {
      Contact: () => import('#transport/cms/controllers/front/contact_controller'),
      Page: () => import('#transport/cms/controllers/front/page_controller'),
    },
  },
  core: {
    admin: {
      Dashboard: () => import('#transport/core/controllers/admin/dashboard_controller'),
      Maintenance: () => import('#transport/core/controllers/admin/maintenance_controller'),
    },
    api: {
      DashboardApi: () => import('#transport/core/controllers/api/dashboard_api_controller'),
      MaintenanceApi: () => import('#transport/core/controllers/api/maintenance_api_controller'),
      Openapi: () => import('#transport/core/controllers/api/openapi_controller'),
    },
    front: {
      Docs: () => import('#transport/core/controllers/front/docs_controller'),
      Home: () => import('#transport/core/controllers/front/home_controller'),
      Robots: () => import('#transport/core/controllers/front/robots_controller'),
      Sitemap: () => import('#transport/core/controllers/front/sitemap_controller'),
    },
    Health: () => import('#transport/core/controllers/health_controller'),
  },
  file: {
    admin: {
      FileFolders: () => import('#transport/file/controllers/admin/file_folders_controller'),
      Files: () => import('#transport/file/controllers/admin/files_controller'),
    },
    api: {
      File: () => import('#transport/file/controllers/api/file_controller'),
      FilesAltApi: () => import('#transport/file/controllers/api/files_alt_api_controller'),
      FilesApi: () => import('#transport/file/controllers/api/files_api_controller'),
      FilesDeleteApi: () => import('#transport/file/controllers/api/files_delete_api_controller'),
      FilesShowApi: () => import('#transport/file/controllers/api/files_show_api_controller'),
      FilesUploadApi: () => import('#transport/file/controllers/api/files_upload_api_controller'),
      FoldersApi: () => import('#transport/file/controllers/api/folders_api_controller'),
      FoldersDeleteApi: () => import('#transport/file/controllers/api/folders_delete_api_controller'),
      FoldersShowApi: () => import('#transport/file/controllers/api/folders_show_api_controller'),
      FoldersUpdateApi: () => import('#transport/file/controllers/api/folders_update_api_controller'),
    },
  },
  identity: {
    admin: {
      Permissions: () => import('#transport/identity/controllers/admin/permissions_controller'),
      PermissionsCreate: () => import('#transport/identity/controllers/admin/permissions_create_controller'),
      PermissionsUpdate: () => import('#transport/identity/controllers/admin/permissions_update_controller'),
      Roles: () => import('#transport/identity/controllers/admin/roles_controller'),
      RolesCreate: () => import('#transport/identity/controllers/admin/roles_create_controller'),
      RolesShow: () => import('#transport/identity/controllers/admin/roles_show_controller'),
      RolesUpdate: () => import('#transport/identity/controllers/admin/roles_update_controller'),
      Users: () => import('#transport/identity/controllers/admin/users_controller'),
      UsersCreate: () => import('#transport/identity/controllers/admin/users_create_controller'),
      UsersShow: () => import('#transport/identity/controllers/admin/users_show_controller'),
      UsersUpdate: () => import('#transport/identity/controllers/admin/users_update_controller'),
    },
    api: {
      PermissionsApi: () => import('#transport/identity/controllers/api/permissions_api_controller'),
      RolesApi: () => import('#transport/identity/controllers/api/roles_api_controller'),
      RolesCreateApi: () => import('#transport/identity/controllers/api/roles_create_api_controller'),
      RolesDeleteApi: () => import('#transport/identity/controllers/api/roles_delete_api_controller'),
      RolesShowApi: () => import('#transport/identity/controllers/api/roles_show_api_controller'),
      RolesUpdateApi: () => import('#transport/identity/controllers/api/roles_update_api_controller'),
      UsersApi: () => import('#transport/identity/controllers/api/users_api_controller'),
      UsersCreateApi: () => import('#transport/identity/controllers/api/users_create_api_controller'),
      UsersDeleteApi: () => import('#transport/identity/controllers/api/users_delete_api_controller'),
      UsersShowApi: () => import('#transport/identity/controllers/api/users_show_api_controller'),
      UsersUpdateApi: () => import('#transport/identity/controllers/api/users_update_api_controller'),
    },
  },
  log: {
    admin: {
      Logs: () => import('#transport/log/controllers/admin/logs_controller'),
    },
    api: {
      LogsApi: () => import('#transport/log/controllers/api/logs_api_controller'),
    },
  },
  webhook: {
    admin: {
      Deliveries: () => import('#transport/webhook/controllers/admin/deliveries_controller'),
    },
    api: {
      DeliveriesApi: () => import('#transport/webhook/controllers/api/deliveries_api_controller'),
    },
    WebhookReceiver: () => import('#transport/webhook/controllers/webhook_receiver_controller'),
  },
}
