/**
 * `api` flavor manifest.
 *
 * Derives the headless REST flavor from `main`: prunes the entire Inertia/Vite
 * view layer (the `inertia/` tree, providers, configs, asset tooling and every
 * session-rendered controller), the public site surface (home, sitemap,
 * robots, contact) AND the whole CMS module (page/template/builder + Transmit)
 * — the CMS lives on `main` only. What remains is a pure token-guarded REST
 * backend.
 *
 * Everything the flavor keeps is reachable through the versioned REST layer
 * (`/api/v1/*`, issue #7) behind the API token guard (#6):
 * - the non-CMS domain layer (models, migrations, repositories, services,
 *   actions, transformers, validators) — auth, files, logs, maintenance;
 * - `@adonisjs/drive` with public file serving, Redis, mail, i18n, the rate
 *   limiter, shield and a first-class env-driven CORS policy.
 *
 * Because the CMS is pruned, this manifest reuses the `inertia` flavor's CMS
 * delete inventory (the co-located `src/cms` and `app/cms` units, CMS
 * migrations/seeders/factories, i18n, the contact email template, the CMS
 * ace command, Transmit) and its composition rewrites (`start/routes.ts`,
 * events, nav, dashboard, sitemap, container, `config/shield.ts`,
 * `config/database.ts`).
 *
 * The shared design-system workspace (`packages/design-system`) is pruned
 * wholesale — the headless flavor ships no frontend to consume it — and the
 * app workspace's dependency on it is dropped through the manifest's
 * `dependencies` field. The root `workspaces` glob field stays
 * flavor-invariant (identical to main's `apps/*` + `packages/*`): a glob
 * matching nothing is valid, so the prune needs no root-manifest variation.
 *
 * Per the "variation only in config/composition/docs files" rule, the
 * rewrite set is exactly the allowlisted composition files: the route module
 * index, feature flags, CORS, the view-layer asset middleware seam, the
 * boot/serve assembly (`adonisrc.ts`), environment validation, the env
 * template, `package.json`, `tsconfig.json` and the README. The `package.json`
 * rewrite carries the script and import-map adjustments; the frontend and
 * Transmit dependencies are then pruned by name through the manifest's
 * `dependencies` field, exactly like the `inertia` flavor. Any coupling
 * discovered between kept code and the pruned view/CMS layer while
 * implementing was resolved by refactoring `main`, never by patching this
 * manifest.
 *
 * The auth endpoints (`/api/v1/auth`) and the admin REST surface
 * (`/api/v1/admin`) are exactly the non-CMS ones built on `main` in #6 and #7
 * — this flavor adds no endpoints, it only removes the view layer and the
 * CMS.
 *
 * Applied by {@link '../engine'} via
 * `node --import @poppinss/ts-exec tooling/prune/apply.ts api`.
 */
import type { FlavorManifest } from '#prune/types';

const apiManifest: FlavorManifest = {
	flavor: 'api',

	delete: [
		// ─── Frontend tree (Inertia/React/Vite/Tailwind) ─────────────────────
		'apps/web/inertia',
		'apps/web/tsconfig.inertia.json',
		'apps/web/vite.config.ts',
		'apps/web/vitest.config.ts',
		'apps/web/config/inertia.ts',
		'apps/web/config/vite.ts',

		// ─── Design-system package (shared React front) — main + inertia only ──
		// The headless `api` flavor ships no frontend, so the design-system
		// workspace is pruned wholesale (its dependency is dropped from the app
		// manifest through the `dependencies` prune below).
		'packages/design-system',

		// ─── View-layer server middleware ────────────────────────────────────
		'apps/web/app/core/middleware/inertia_middleware.ts',

		// ─── Page transport adapter — Inertia-dependent half of the REST ─────
		// contract. rest_adapter.ts stays (transport-agnostic); only this
		// pipeline and its unit tests need the pruned Inertia binding.
		'apps/web/app/core/rest/page_adapter.ts',

		// ─── Inertia render helper — dead once every front/admin controller ──
		// and the page adapter are pruned. Its only importers above are all
		// deleted in this flavor, and it imports the pruned @adonisjs/inertia
		// package, so it (and its spec) must go with the view layer.
		'apps/web/app/core/helpers/inertia_render.ts',
		'apps/web/tests/unit/core/helpers/inertia_render.spec.ts',

		// ─── Session-rendered front controllers ──────────────────────────────
		// front = guest/public pages (auth, self-service, home, sitemap, robots).
		'apps/web/app/auth/controllers/front',
		'apps/web/app/account/controllers/front',
		'apps/web/app/core/controllers/front',

		// ─── Session-guarded Inertia admin controllers ───────────────────────
		// The identity domain keeps its business layer and REST controllers;
		// only the Inertia render controllers are pruned, like every other
		// domain. The admin routes file dies with its controllers
		// (`controllers/admin/routes.ts`); the domain entry
		// (`app/identity/routes.ts`) is pruned too because it imports the
		// admin surface — the `start/routes.ts` rewrite points straight at
		// the API surface instead.
		'apps/web/app/core/controllers/admin',
		'apps/web/app/identity/controllers/admin',
		'apps/web/app/identity/routes.ts',
		'apps/web/app/file/controllers/admin',
		'apps/web/app/file/routes.ts',
		'apps/web/app/log/controllers/admin',
		'apps/web/app/log/routes.ts',

		// ─── CMS module (page/template/builder) — main-only ───────────────────
		// The whole CMS domain is pruned: the co-located units (the `src/cms`
		// business layer, the `app/cms` transport layer with its admin, front
		// and api controllers, CMS migrations/seeders/factories, the
		// `resources/lang/{en,fr}/cms` i18n namespaces, the contact email
		// template, the CMS ace command) — mirroring the `inertia` flavor's
		// CMS delete map. The CMS React subtrees die with the whole
		// `apps/web/inertia` tree above.
		'apps/web/src/cms',
		'apps/web/app/cms',
		'apps/web/database/migrations/cms',
		'apps/web/database/seeders/cms',
		'apps/web/database/factories/cms',
		'apps/web/resources/lang/en/cms',
		'apps/web/resources/lang/fr/cms',
		'apps/web/resources/views/emails/contact_form_email.edge',
		'apps/web/commands/cms_normalize_migration_names.ts',

		// ─── Transmit (real-time builder collaboration) — CMS-only ────────────
		'apps/web/start/transmit.ts',
		'apps/web/config/transmit.ts',
		'apps/web/config/cms.ts',

		// ─── Route modules — unreferenced after the start/routes.ts rewrite ───
		// The domain entries die with the pruned front surface — the api flavor
		// self-registers the token API directly from
		// `#transport/auth/controllers/api/routes`, `#transport/account/controllers/api/routes`
		// and `#transport/core/controllers/api/routes` in the start/routes.ts rewrite;
		// the health probes come from `#transport/core/health.routes`.
		'apps/web/app/auth/routes.ts',
		'apps/web/app/account/routes.ts',
		'apps/web/app/core/routes.ts',

		// ─── Front test suites (session-guarded Inertia-page functional, ──────
		// ─── SEO, and the full-router structure snapshots of the pruned routes)
		'apps/web/tests/functional/core',
		'apps/web/tests/functional/log',
		'apps/web/tests/functional/auth/accept_invitation.spec.ts',
		'apps/web/tests/functional/auth/email_verification.spec.ts',
		'apps/web/tests/functional/auth/forgot_password.spec.ts',
		'apps/web/tests/functional/auth/oauth.spec.ts',
		'apps/web/tests/functional/auth/password_reset_queue.spec.ts',
		'apps/web/tests/functional/auth/register.spec.ts',
		'apps/web/tests/functional/auth/reset_password.spec.ts',
		'apps/web/tests/functional/auth/session.spec.ts',
		'apps/web/tests/functional/auth/token_consume.spec.ts',
		'apps/web/tests/functional/auth/two_factor.spec.ts',
		'apps/web/tests/functional/account/email_change.spec.ts',
		'apps/web/tests/integration/routes_structure.spec.ts',
		'apps/web/tests/unit/core/rest/page_adapter.spec.ts',

		// ─── CMS test suites ──────────────────────────────────────────────────
		'apps/web/tests/unit/cms',
		'apps/web/tests/integration/cms',
		'apps/web/tests/functional/cms',
		'apps/web/tests/helpers/page_search.ts',

		// ─── Inbound webhook module (main-only) ─────────────────────────────────
		'apps/web/src/webhook',
		'apps/web/app/webhook',
		'apps/web/config/webhooks.ts',
		'apps/web/database/migrations/webhook',
		'apps/web/database/factories/webhook',
		'apps/web/resources/lang/en/webhook.json',
		'apps/web/resources/lang/fr/webhook.json',
		'apps/web/tests/unit/webhook',
		'apps/web/tests/integration/webhook',
		'apps/web/tests/functional/webhook',

		// ─── Prune pipeline (main-only infrastructure) ────────────────────────
		'tooling/prune',
		'apps/web/tests/unit/prune',

		// ─── Generated indexes — regenerated headless against the pruned ──────
		// ─── tree so zero view-layer references survive (init hooks + ready ────
		// ─── hook + Tuyau routesScanned regenerate the whole .adonisjs dir). ────
		'apps/web/.adonisjs',
	],

	rewrites: [
		// ─── config/features.ts — drop the session UI surfaces ───────────────
		{
			path: 'apps/web/config/features.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Feature flags',
				'|--------------------------------------------------------------------------',
				'|',
				'| Runtime toggles to enable or disable route modules.',
				'| All features are enabled by default — change a boolean to',
				'| deactivate a module at runtime without touching routing code.',
				'|',
				'| The `api` flavor prunes the entire Inertia/Vite view layer AND the',
				'| CMS module (the CMS lives on `main` only): the session-rendered',
				'| auth, settings and admin surfaces are `false`, `cms` is `false`, and',
				'| only the non-CMS token-guarded REST layer (`adminApi`) stays on.',
				'*/',
				'',
				'export default {',
				'  auth: false,',
				'  settings: false,',
				'  admin: false,',
				'  adminApi: true,',
				'  apiDocs: true,',
				'  cms: false,',
				'  maintenance: true,',
				'} as const',
				'',
			].join('\n'),
		},

		// ─── start/routes.ts — REST-only route module index ──────────────────
		{
			path: 'apps/web/start/routes.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Routes file',
				'|--------------------------------------------------------------------------',
				'|',
				'| Route module index — each domain registers its own routes.',
				'| Feature flags in config/features.ts gate each module at runtime.',
				'|',
				'| The `api` flavor is headless: no Inertia routes, no public site. The',
				'| whole backend is the versioned REST surface — the identity/token',
				'| API (`/api/v1/auth`, ...) and the admin REST API (`/api/v1/admin`, ...)',
				'| — plus the OAuth redirect/callback pair (social login issues an API',
				'| token and redirects to `AUTH_API_CLIENT_URL`) and the health endpoints',
				'| outside the maintenance wrapper.',
				'*/',
				'',
				'// Domain token API routes self-register on import (feature-gated inside the modules).',
				"import '#transport/auth/controllers/api/routes'",
				"import '#transport/account/controllers/api/routes'",
				"import '#transport/core/controllers/api/routes'",
				"import '#transport/file/controllers/api/routes'",
				"import '#transport/identity/controllers/api/routes'",
				"import '#transport/log/controllers/api/routes'",
				"import router from '@adonisjs/core/services/router'",
				"import { registerCoreHealthRoutes } from '#transport/core/health.routes'",
				"import { controllers } from '#generated/controllers'",
				"import features from '#config/features'",
				"import { middleware } from '#start/kernel'",
				'',
				'// Health routes are outside maintenance middleware (liveness/readiness probes)',
				'registerCoreHealthRoutes()',
				'',
				'// Wrap all feature routes with maintenance middleware',
				'// Health routes are registered separately above (outside this wrapper)',
				'',
				'router',
				'  .group(() => {',
				'    // OAuth redirect + callback — the browser round-trip completes here and',
				'    // the callback issues an API token (spec #6 social API mode).',
				'    router',
				'      .group(() => {',
				"        router.get('/:provider', [controllers.auth.api.SocialApi, 'redirect']).as('redirect')",
				'        router',
				"          .get('/:provider/callback', [controllers.auth.api.SocialApi, 'callback'])",
				"          .as('callback')",
				'      })',
				"      .prefix('oauth')",
				"      .as('auth.social')",
				'',
				'    // The admin REST surface (core dashboard + maintenance) self-registers',
				'    // on import from `#transport/core/controllers/api/routes` and gates itself',
				'    // on `adminApi` (and the `api` guard) inside its route module.',
				'  })',
				'  .use(features.maintenance ? middleware.maintenance() : [])',
				'',
			].join('\n'),
		},

		// ─── config/database.ts — drop the CMS migration folder ─────────────────
		{
			path: 'apps/web/config/database.ts',
			content: [
				"import app from '@adonisjs/core/services/app'",
				"import { defineConfig } from '@adonisjs/lucid'",
				'',
				'const dbConfig = defineConfig({',
				'  /**',
				'   * Default connection used for all queries.',
				'   */',
				"  connection: 'pg',",
				'',
				'  connections: {',
				'    /**',
				'     * SQLite connection (default).',
				'     */',
				'    sqlite: {',
				"      client: 'better-sqlite3',",
				'',
				'      connection: {',
				'        /**',
				'         * Database file location.',
				'         */',
				"        filename: app.tmpPath('db.sqlite3'),",
				'      },',
				'',
				'      /**',
				'       * Required by Knex for SQLite defaults.',
				'       */',
				'      useNullAsDefault: true,',
				'',
				'      migrations: {',
				'        /**',
				'         * Sort migration files naturally by filename.',
				'         */',
				'        naturalSort: true,',
				'',
				'        /**',
				'         * Paths containing migration files. The `api` flavor prunes the',
				'         * CMS module, so `database/migrations/cms` is absent.',
				'         */',
				"        paths: ['database/migrations'],",
				'      },',
				'    },',
				'',
				'    /**',
				'     * PostgreSQL connection.',
				'     * Install package to switch: npm install pg',
				'     */',
				'    pg: {',
				"      client: 'pg',",
				'      connection: {',
				'        host: process.env.PG_HOST,',
				'        port: Number(process.env.PG_PORT || 5432),',
				'        user: process.env.PG_USER,',
				'        password: process.env.PG_PASSWORD,',
				'        database: process.env.PG_DB_NAME,',
				'      },',
				'      migrations: {',
				'        naturalSort: true,',
				"        paths: ['database/migrations'],",
				'      },',
				'      debug: app.inDev,',
				'    },',
				'',
				'    /**',
				'     * MySQL / MariaDB connection.',
				'     * Install package to switch: npm install mysql2',
				'     */',
				'    // mysql: {',
				'    //   client: "mysql2",',
				'    //   connection: {',
				'    //     host: process.env.MYSQL_HOST,',
				'    //     port: Number(process.env.MYSQL_PORT || 3306),',
				'    //     user: process.env.MYSQL_USER,',
				'    //     password: process.env.MYSQL_PASSWORD,',
				'    //     database: process.env.MYSQL_DB_NAME,',
				'    //   },',
				'    //   migrations: {',
				'    //     naturalSort: true,',
				'    //     paths: ["database/migrations"],',
				'    //   },',
				'    //   debug: app.inDev,',
				'    // },',
				'',
				'    /**',
				'     * Microsoft SQL Server connection.',
				'     * Install package to switch: npm install tedious',
				'     */',
				'    // mssql: {',
				'    //   client: "mssql",',
				'    //   connection: {',
				'    //     server: process.env.MSSQL_SERVER,',
				'    //     port: Number(process.env.MSSQL_PORT || 1433),',
				'    //     user: process.env.MSSQL_USER,',
				'    //     password: process.env.MSSQL_PASSWORD,',
				'    //     database: process.env.MSSQL_DB_NAME,',
				'    //   },',
				'    //   migrations: {',
				'    //     naturalSort: true,',
				'    //     paths: ["database/migrations"],',
				'    //   },',
				'    //   debug: app.inDev,',
				'    // },',
				'',
				'    /**',
				'     * libSQL (Turso) connection.',
				'     * Install package to switch: npm install @libsql/client',
				'     */',
				'    // libsql: {',
				'    //   client: "libsql",',
				'    //   connection: {',
				'    //     url: process.env.LIBSQL_URL,',
				'    //     authToken: process.env.LIBSQL_AUTH_TOKEN,',
				'    //   },',
				'    //   useNullAsDefault: true,',
				'    //   migrations: {',
				'    //     naturalSort: true,',
				'    //     paths: ["database/migrations"],',
				'    //   },',
				'    //   debug: app.inDev,',
				'    // },',
				'  },',
				'})',
				'',
				'export default dbConfig',
				'',
			].join('\n'),
		},

		// ─── config/shield.ts — drop the CMS iframe frame-src hosts ─────────────
		{
			path: 'apps/web/config/shield.ts',
			content: [
				"import app from '@adonisjs/core/services/app'",
				"import { defineConfig } from '@adonisjs/shield'",
				'',
				'/**',
				' * CSP configuration for the `api` flavor.',
				' *',
				' * The CMS `iframe` block (and its `frame-src` host allowlist) is pruned in',
				' * this flavor, so the CMS-specific imports are gone and the `frame-src`',
				' * directive falls back to the default origin-only policy.',
				' */',
				'const shieldConfig = defineConfig({',
				'  /**',
				'   * Configure CSP policies for your app. Refer documentation',
				'   * to learn more.',
				'   */',
				'  csp: {',
				'    /**',
				'     * Enable the Content-Security-Policy header.',
				'     */',
				'    enabled: true,',
				'',
				'    /**',
				'     * Report violations without blocking resources in dev/test.',
				'     * Enforce in production.',
				'     */',
				'    reportOnly: app.inDev || app.inTest,',
				'',
				'    /**',
				'     * Per-resource CSP directives.',
				'     */',
				'    directives: {',
				'      // Default: only same-origin',
				'      defaultSrc: ["\'self\'"],',
				'',
				'      // Scripts: self + Vite HMR in dev/test',
				'      scriptSrc: [',
				'        "\'self\'",',
				'        ...(app.inDev || app.inTest ? ["\'unsafe-eval\'", "\'unsafe-inline\'"] : []), // Vite HMR needs these in dev/test',
				'      ],',
				'',
				'      // Styles: self + Tailwind JIT inline styles',
				'      styleSrc: ["\'self\'", "\'unsafe-inline\'"],',
				'',
				'      // Images: self + data: URIs + HTTPS',
				"      imgSrc: [\"'self'\", 'data:', 'https:'],",
				'',
				'      // Fonts: self + data: (for inline fonts)',
				"      fontSrc: [\"'self'\", 'data:'],",
				'',
				'      // Connect: self + SSE + Vite HMR websocket + Sentry',
				'      connectSrc: [',
				'        "\'self\'",',
				"        ...(app.inDev || app.inTest ? ['ws:', 'wss:'] : []), // Vite HMR websocket",
				"        'https://*.sentry.io', // Sentry error reporting",
				'      ],',
				'',
				'      // Frames: default to same-origin only — the CMS iframe block is pruned.',
				'      frameSrc: ["\'self\'"],',
				'',
				'      // Frames: deny (xFrame also set to SAMEORIGIN)',
				'      frameAncestors: ["\'none\'"],',
				'',
				'      // Forms: self only',
				'      formAction: ["\'self\'"],',
				'',
				'      // Base URI: self',
				'      baseUri: ["\'self\'"],',
				'',
				'      // Object/embed: none',
				'      objectSrc: ["\'none\'"],',
				'',
				'      // Media: self + external direct video files (video block)',
				"      mediaSrc: [\"'self'\", 'https:'],",
				'',
				'      // Workers: self',
				'      workerSrc: ["\'self\'"],',
				'',
				'      // Manifest: self',
				'      manifestSrc: ["\'self\'"],',
				'    },',
				'  },',
				'',
				'  /**',
				'   * Configure CSRF protection options. Refer documentation',
				'   * to learn more.',
				'   */',
				'  csrf: {',
				'    /**',
				'     * Enable CSRF token verification for state-changing requests.',
				'     */',
				'    enabled: true,',
				'',
				'    /**',
				'     * Routes to exclude from CSRF checks. Useful for external webhooks or',
				'     * API endpoints. Patterns match `ctx.route.pattern` exactly (no glob),',
				'     * hence the function form.',
				'     *',
				'     * `/api/v1/*` is the token-guarded REST API: Bearer-token requests carry',
				'     * no cookies, so they are not exposed to CSRF. Session-authenticated API',
				'     * routes (`/api/admin/*`, `/api/settings/*`) keep full CSRF protection.',
				'     */',
				'    exceptRoutes: (ctx) =>',
				"      ctx.route !== undefined && ctx.route.pattern.replace(/^\\//, '').startsWith('api/v1/'),",
				'',
				'    /**',
				'     * Expose an encrypted XSRF-TOKEN cookie for frontend HTTP clients.',
				'     */',
				'    enableXsrfCookie: true,',
				'',
				'    /**',
				'     * HTTP methods protected by CSRF validation.',
				'     */',
				"    methods: ['POST', 'PUT', 'PATCH', 'DELETE'],",
				'  },',
				'',
				'  /**',
				'   * Control how your website should be embedded inside',
				'   * iframes.',
				'   */',
				'  xFrame: {',
				'    /**',
				'     * Enable the X-Frame-Options header.',
				'     */',
				'    enabled: true,',
				'',
				'    /**',
				'     * Block all framing attempts. Default value is DENY.',
				'     */',
				"    action: 'SAMEORIGIN',",
				'  },',
				'',
				'  /**',
				'   * Force browser to always use HTTPS.',
				'   */',
				'  hsts: {',
				'    /**',
				'     * Enable the Strict-Transport-Security header.',
				'     */',
				'    enabled: true,',
				'',
				'    /**',
				'     * HSTS policy duration remembered by browsers.',
				'     */',
				"    maxAge: '180 days',",
				'  },',
				'',
				'  /**',
				'   * Disable browsers from sniffing content types and rely only',
				'   * on the response content-type header.',
				'   */',
				'  contentTypeSniffing: {',
				'    /**',
				'     * Enable X-Content-Type-Options: nosniff.',
				'     */',
				'    enabled: true,',
				'  },',
				'})',
				'',
				'export default shieldConfig',
				'',
			].join('\n'),
		},

		// ─── start/events.ts — no event-driven flows remain ─────────────────────
		{
			path: 'apps/web/start/events.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Events',
				'|--------------------------------------------------------------------------',
				'|',
				'| The `api` flavor has no event-driven flows: the auth and account mail',
				'| flows deliver through the mail client directly (no event bus), and the',
				'| CMS contact-form listener is pruned. This file intentionally registers',
				'| nothing; the empty export keeps it a module so the dynamic import in',
				'| adonisrc.ts typechecks under the client tsconfig.',
				'|',
				'*/',
				'',
				'export {}',
				'',
			].join('\n'),
		},

		// ─── start/nav.ts — drop the page + template nav entries ────────────────
		{
			path: 'apps/web/start/nav.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Admin navigation composition',
				'|--------------------------------------------------------------------------',
				'|',
				'| Registers the admin navigation entries of every domain existing in this',
				'| flavor of the application, in sidebar order. This file is part of the',
				"| composition set that flavor manifests may rewrite: remove a domain's",
				'| registration and its entries disappear from the admin sidebar.',
				'|',
				'*/',
				'',
				"import app from '@adonisjs/core/services/app'",
				"import { coreNavEntries, maintenanceNavEntries } from '#transport/core/nav'",
				"import { fileNavEntries } from '#transport/file/nav'",
				"import { identityNavEntries } from '#transport/identity/nav'",
				"import { loggingNavEntries } from '#transport/log/nav'",
				"import { NavRegistry } from '#core/services/nav_registry'",
				'',
				'app.container.singleton(NavRegistry, () => new NavRegistry())',
				'',
				'const registry = await app.container.make(NavRegistry)',
				'',
				"registry.register('core', coreNavEntries)",
				"registry.register('file', fileNavEntries)",
				"registry.register('identity', identityNavEntries)",
				"registry.register('maintenance', maintenanceNavEntries)",
				"registry.register('logging', loggingNavEntries)",
				'',
			].join('\n'),
		},

		// ─── start/permissions.ts — drop the page + template catalogs ───────────
		{
			path: 'apps/web/start/permissions.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| System Permission Catalog',
				'|--------------------------------------------------------------------------',
				'|',
				'| The composed list of system permission slugs for this flavor. Every',
				'| domain owns its own catalog const in its business layer (e.g.',
				'| `src/identity/permissions.ts`); this file composes those per-domain',
				'| catalogs into the single matrix the permission seeder persists.',
				"| Adding or renaming a permission only touches that domain's catalog file.",
				'|',
				'| The `permissionCatalog` object also drives the `PermissionSlug` union of',
				'| this flavor: the catalog is the single source of both the persisted slug',
				'| values and the slug type.',
				'|',
				'| The composed catalog finally yields the `permissions` identity map — one',
				'| group per category, one camelCase key per action, mapped to the raw slug',
				'| string — which route guards, nav entries and ability checks reference',
				'| instead of raw literals.',
				'|',
				'*/',
				'',
				"import { corePermissionCatalog, coreRoleSlugs, maintenancePermissionCatalog } from '#core/permissions'",
				"import { filePermissionCatalog } from '#file/permissions'",
				"import { identityPermissionCatalog } from '#identity/permissions'",
				"import { loggingPermissionCatalog } from '#log/permissions'",
				"import type { PermissionSlugs, PermissionMap } from '#types/permissions'",
				'',
				'/**',
				' * The composed system permission catalog of this flavor: `category →',
				' * actions` matrix ordered by domain (core, identity, file, maintenance,',
				' * logging). The permission seeder persists exactly this matrix, so it',
				' * is the single source of the persisted slugs.',
				' */',
				'export const permissionCatalog = {',
				'  ...corePermissionCatalog,',
				'  ...identityPermissionCatalog,',
				'  ...filePermissionCatalog,',
				'  ...maintenancePermissionCatalog,',
				'  ...loggingPermissionCatalog,',
				'}',
				'',
				'/** Union of every system permission slug in this flavor. */',
				'export type PermissionSlug = PermissionSlugs<typeof permissionCatalog>',
				'',
				'/**',
				' * The camelCase form of a snake_case permission action (`manage_roles` →',
				' * `manageRoles`); the runtime counterpart of the nested `permissions` keys.',
				' */',
				'const actionKey = (action: string): string =>',
				'  action.replace(/_([a-z])/g, (_separator, letter: string) => letter.toUpperCase())',
				'',
				'/**',
				' * Builds the nested permission identity map from a composed permission',
				' * catalog.',
				' *',
				' * The generic signature carries the {@link PermissionMap} type through the',
				" * construction, so the map's shape is derived from the catalog's type",
				' * instead of being imposed by an `as unknown as` cast at the composition.',
				' * The single cast inside the loop is confined to the runtime key iteration —',
				' * the group is typed exactly as its target and filled exhaustively, one',
				' * entry per catalog action.',
				' *',
				' * @param catalog - The composed `category → actions` permission catalog.',
				' * @returns The nested `category → camelCase action → slug` identity map.',
				' */',
				'function buildPermissionMap<Catalog extends Record<string, readonly string[]>>(',
				'  catalog: Catalog,',
				'): PermissionMap<Catalog> {',
				'  const map = {} as PermissionMap<Catalog>',
				'',
				'  for (const category of Object.keys(catalog) as Array<keyof Catalog & string>) {',
				'    const group = {} as PermissionMap<Catalog>[typeof category]',
				'',
				'    for (const action of catalog[category]) {',
				'      (group as Record<string, string>)[actionKey(action)] = `${category}.${action}`',
				'    }',
				'',
				'    map[category] = group',
				'  }',
				'',
				'  return map',
				'}',
				'',
				'/**',
				" * The nested identity map of this flavor's permission slugs: one group per",
				' * catalog category (`permissions.users`, `permissions.pages`, ...) whose',
				" * keys are the camelCase form of the category's actions",
				' * (`permissions.users.view`, `permissions.users.manageRoles`, ...) mapped to',
				' * the raw slug string. Derived at runtime from the {@link permissionCatalog},',
				' * so renaming a slug in a domain catalog file renames its key here, and',
				' * every former `permissions.*` use site fails to compile until it is updated.',
				' */',
				'export const permissions = buildPermissionMap(permissionCatalog)',
				'',
				'/**',
				' * The system role slugs of this flavor; the role seeder persists exactly',
				' * this list, so it is the single source of the persisted role slugs.',
				' */',
				'export const systemRoleSlugs = coreRoleSlugs',
				'',
				'/** Union of every system role slug in this flavor. */',
				'export type SystemRoleSlug = (typeof systemRoleSlugs)[number]',
				'',
			].join('\n'),
		},

		// ─── start/dashboard.ts — drop the page + template collectors ───────────
		{
			path: 'apps/web/start/dashboard.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Dashboard composition',
				'|--------------------------------------------------------------------------',
				'|',
				'| Registers the dashboard section collectors of every domain existing in',
				'| this flavor of the application. This file is part of the composition set',
				"| that flavor manifests may rewrite: remove a domain's registration and",
				'| its section disappears from the admin dashboard.',
				'|',
				'*/',
				'',
				"import app from '@adonisjs/core/services/app'",
				"import { FileDashboardCollector } from '#file/services/file_dashboard_collector'",
				"import { IdentityDashboardCollector } from '#identity/services/identity_dashboard_collector'",
				"import { DashboardRegistry } from '#core/services/dashboard_registry'",
				'',
				'app.container.singleton(DashboardRegistry, () => new DashboardRegistry())',
				'',
				'const registry = await app.container.make(DashboardRegistry)',
				'',
				"registry.register('identity', () => app.container.make(IdentityDashboardCollector))",
				"registry.register('file', () => app.container.make(FileDashboardCollector))",
				'',
			].join('\n'),
		},

		// ─── start/sitemap.ts — drop the page contributor (routes only) ─────────
		{
			path: 'apps/web/start/sitemap.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Sitemap composition',
				'|--------------------------------------------------------------------------',
				'|',
				'| Registers the sitemap contributors of every domain existing in this',
				'| flavor of the application. This file is part of the composition set',
				"| that flavor manifests may rewrite: remove a domain's registration and",
				'| its URLs disappear from `sitemap.xml`.',
				'|',
				'| The route collector is always present (hand-written `core.*.render`',
				'| routes exist in every flavor with a public front). The page collector is',
				'| CMS-specific and is removed by the `inertia` flavor manifest.',
				'|',
				'*/',
				'',
				"import app from '@adonisjs/core/services/app'",
				"import { RouteSitemapCollector } from '#core/services/route_sitemap_collector'",
				"import { SitemapRegistry } from '#core/services/sitemap_registry'",
				'',
				'app.container.singleton(SitemapRegistry, () => new SitemapRegistry())',
				'',
				'const registry = await app.container.make(SitemapRegistry)',
				'',
				"registry.register('routes', () => app.container.make(RouteSitemapCollector))",
				'',
			].join('\n'),
		},

		// ─── start/container.ts — drop the builder session binding ──────────────
		{
			path: 'apps/web/start/container.ts',
			content: [
				"import app from '@adonisjs/core/services/app'",
				"import { BackupEngine } from '#backup/services/backup_engine'",
				"import { LogService } from '#log/services/log_service'",
				"import { MaintenanceService } from '#core/services/maintenance_service'",
				"import { CacheService } from '#shared/services/cache_service'",
				"import { RedisCacheDriver } from '#shared/services/cache/drivers/redis_cache_driver'",
				"import { InMemoryCacheDriver } from '#shared/services/cache/drivers/in_memory_cache_driver'",
				"import { LockService } from '#shared/services/lock_service'",
				'',
				'/**',
				' * IoC container bindings.',
				' *',
				' * Singleton services are instantiated exactly once per process and reused',
				' * across every request — which is what makes in-flight state (locks,',
				' * sessions) work correctly without serialising to a database on every call.',
				' * Factory bindings are re-created on each resolution with runtime arguments',
				' * supplied via {@link app.container.make}.',
				' *',
				" * Add this file to `adonisrc.ts` preloads if it isn't already:",
				' *',
				' * @example',
				' * // adonisrc.ts',
				' * preloads: [',
				" *   () => import('#start/container'),",
				' * ]',
				' */',
				'',
				'// ─── BackupEngine (factory) ────────────────────────────────────────────',
				'',
				'/**',
				' * Factory binding for {@link BackupEngine} so that callers can resolve it',
				' * through the container instead of using `new`. Runtime arguments',
				' * (`strategyType`, `tempDir`) are supplied at resolution time which keeps',
				' * the strategy dynamic while still being mockable in tests via',
				' * {@link app.container.swap}.',
				' *',
				' * @example',
				" * const engine = await app.container.make(BackupEngine, ['full', 'storage/temp/backups'])",
				' */',
				'app.container.bind(BackupEngine, async (resolver, runtimeValues) => {',
				'  const [strategyType, tempDir] = runtimeValues ?? []',
				'  const logService = await resolver.make(LogService)',
				'  return new BackupEngine(strategyType, tempDir, logService)',
				'})',
				'',
				'// ─── CacheService (singleton) ──────────────────────────────────────────',
				'',
				'/**',
				' * The root `CacheService` backed by Redis.',
				' * Inject or resolve via the container anywhere in the app:',
				' *',
				' * @example',
				' * // In a service or controller',
				' * const cache = await app.container.make(CacheService)',
				' */',
				'app.container.singleton(CacheService, () => {',
				'  const driver = new RedisCacheDriver()',
				'  return new CacheService(driver)',
				'})',
				'',
				'// ─── InMemoryCacheDriver (singleton) ──────────────────────────────────────────',
				'',
				'/**',
				' * In-memory {@link CacheDriver} implementation singleton, for tests and',
				' * single-process environments. The production {@link CacheService} binding',
				' * above stays on Redis; resolve or swap this driver through the container',
				' * wherever the contract is needed.',
				' *',
				' * @example',
				' * const driver = await app.container.make(InMemoryCacheDriver)',
				" * const cache = new CacheService(driver).namespace('builder')",
				' */',
				'app.container.singleton(InMemoryCacheDriver, () => new InMemoryCacheDriver());',
				'',
				'// ─── LockService (singleton) ──────────────────────────────────────────────',
				'',
				'/**',
				' * Distributed lock service singleton.',
				' * Shared across every request and job execution so a maintenance task never',
				' * runs twice at once. Uses Redis with an in-memory fallback.',
				' *',
				' * @example',
				' * const locks = await app.container.make(LockService)',
				" * await locks.withLock('maintenance:log_prune', 1800, () => runPrune())",
				' */',
				'app.container.singleton(LockService, () => new LockService())',
				'',
				'// ─── MaintenanceService (singleton) ────────────────────────────────────',
				'',
				'/**',
				' * Maintenance service singleton.',
				' * Handles Redis + memory fallback for maintenance mode configuration.',
				' * Initializes memory fallback on first resolution.',
				' */',
				'app.container.singleton(MaintenanceService, async () => {',
				'  const service = MaintenanceService.getInstance()',
				'  await service.initializeMemoryFallback()',
				'  return service',
				'})',
				'',
			].join('\n'),
		},

		// ─── config/cors.ts — explicit env-driven allowlist (first-class) ────
		{
			path: 'apps/web/config/cors.ts',
			content: [
				"import { defineConfig } from '@adonisjs/cors'",
				"import env from '#start/env'",
				'',
				'/**',
				' * Configuration options to tweak the CORS policy. The following',
				' * options are documented on the official documentation website.',
				' *',
				' * https://docs.adonisjs.com/guides/security/cors',
				' */',
				'const corsConfig = defineConfig({',
				'  /**',
				'   * Enable or disable CORS handling globally.',
				'   */',
				'  enabled: true,',
				'',
				'  /**',
				'   * Explicit allowlist of cross-origin front origins, taken from the',
				'   * `CORS_ALLOWED_ORIGINS` environment variable (comma-separated). The',
				'   * `api` flavor is consumed by external fronts by definition, so CORS is',
				'   * a config step — never a code change.',
				'   */',
				'  origin: env',
				"    .get('CORS_ALLOWED_ORIGINS', '')",
				"    .split(',')",
				'    .map((origin) => origin.trim())',
				'    .filter((origin) => origin.length > 0),',
				'',
				'  /**',
				'   * HTTP methods accepted for cross-origin requests.',
				'   */',
				"  methods: ['GET', 'HEAD', 'POST', 'PUT', 'DELETE'],",
				'',
				'  /**',
				'   * Reflect request headers by default. Use a string array to restrict',
				'   * allowed headers.',
				'   */',
				'  headers: true,',
				'',
				'  /**',
				'   * Response headers exposed to the browser.',
				'   */',
				'  exposeHeaders: [],',
				'',
				'  /**',
				'   * Allow cookies/authorization headers on cross-origin requests.',
				'   */',
				'  credentials: true,',
				'',
				'  /**',
				'   * Cache CORS preflight response for N seconds.',
				'   */',
				'  maxAge: 90,',
				'})',
				'',
				'export default corsConfig',
				'',
			].join('\n'),
		},

		// ─── start/asset_middleware.ts — no view-layer asset middleware ──────
		{
			path: 'apps/web/start/asset_middleware.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| View-layer asset middleware composition',
				'|--------------------------------------------------------------------------',
				'|',
				'| The `api` flavor drops the entire Inertia/Vite stack, so no asset',
				'| middleware is registered. `start/kernel.ts` keeps its single',
				'| unconditional reference and this array is simply empty.',
				'|',
				'*/',
				'',
				'export const assetMiddleware = []',
				'',
			].join('\n'),
		},

		// ─── start/env.ts — add the CORS allowlist variable ──────────────────
		{
			path: 'apps/web/start/env.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Environment variables service',
				'|--------------------------------------------------------------------------',
				'|',
				'| The `Env.create` method creates an instance of the Env service. The',
				'| service validates the environment variables and also cast values',
				'| to JavaScript data types.',
				'|',
				'*/',
				'',
				"import { Env } from '@adonisjs/core/env'",
				'',
				"export default await Env.create(new URL('../', import.meta.url), {",
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring node',
				'  |----------------------------------------------------------',
				'  */',
				"  NODE_ENV: Env.schema.enum(['development', 'production', 'test'] as const),",
				'  PORT: Env.schema.number(),',
				"  HOST: Env.schema.string({ format: 'host' }),",
				'  LOG_LEVEL: Env.schema.string(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring app',
				'  |----------------------------------------------------------',
				'  */',
				'  APP_KEY: Env.schema.secret(),',
				"  APP_URL: Env.schema.string({ format: 'url', tld: false }),",
				'  APP_NAME: Env.schema.string(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring CORS',
				'  |----------------------------------------------------------',
				'  |',
				"  | Comma-separated allowlist of external front origins the `api` flavor's",
				'  | REST API accepts cross-origin. Empty by default (no cross-origin',
				'  | browser access until configured).',
				'  |',
				'  */',
				'  CORS_ALLOWED_ORIGINS: Env.schema.string.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring session',
				'  |----------------------------------------------------------',
				'  */',
				"  SESSION_DRIVER: Env.schema.enum(['cookie', 'memory', 'database', 'redis'] as const),",
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the auth guards',
				'  |----------------------------------------------------------',
				'  |',
				'  | Which authentication mechanisms are active. full/inertia keep the',
				'  | session guard and may opt into the token guard (REST API); the api',
				'  | flavor disables the session guard entirely (`AUTH_GUARD_WEB=false`)',
				'  | and authenticates exclusively through API tokens.',
				'  |',
				'  */',
				'  AUTH_GUARD_WEB: Env.schema.boolean.optional(),',
				'  AUTH_GUARD_API: Env.schema.boolean.optional(),',
				'  AUTH_API_TOKEN_EXPIRY: Env.schema.string.optional(),',
				'  AUTH_API_CLIENT_URL: Env.schema.string.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring database connection',
				'  |----------------------------------------------------------',
				'  */',
				"  PG_HOST: Env.schema.string({ format: 'host' }),",
				'  PG_PORT: Env.schema.number(),',
				'  PG_USER: Env.schema.string(),',
				'  PG_PASSWORD: Env.schema.secret(),',
				'  PG_DB_NAME: Env.schema.string(),',
				'',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Variables for configuring @adonisjs/redis package',
				'  |--------------------------------------------------------------------------',
				'  */',
				"  REDIS_HOST: Env.schema.string({ format: 'host' }),",
				'  REDIS_PORT: Env.schema.number(),',
				'  REDIS_PASSWORD: Env.schema.string.optional(),',
				'  REDIS_SOCKET: Env.schema.string.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the queue package',
				'  |----------------------------------------------------------',
				'  */',
				"  QUEUE_DRIVER: Env.schema.enum(['redis', 'sync'] as const),",
				"  QUEUE_CONNECTION: Env.schema.enum(['main', 'local'] as const),",
				'  QUEUE_CONCURRENCY: Env.schema.number.optional(),',
				'  QUEUE_MAX_RETRIES: Env.schema.number.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring scheduled maintenance tasks',
				'  |----------------------------------------------------------',
				'  |',
				'  | Each schedule is a duration string (e.g. "1d", "24h", "30m"); "0" disables',
				'  | the task. The retention windows themselves are resolved in',
				'  | config/maintenance.ts and config/logging.ts.',
				'  |----------------------------------------------------------',
				'  */',
				'  MAINTENANCE_LOG_PRUNE_SCHEDULE: Env.schema.string.optional(),',
				'  MAINTENANCE_BACKUP_RETENTION_SCHEDULE: Env.schema.string.optional(),',
				'  LOG_RETENTION_DAYS: Env.schema.number.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the mail package',
				'  |----------------------------------------------------------',
				'  */',
				"  MAIL_MAILER: Env.schema.enum(['smtp'] as const),",
				'  MAIL_FROM_NAME: Env.schema.string(),',
				'  MAIL_FROM_ADDRESS: Env.schema.string(),',
				'  SMTP_HOST: Env.schema.string(),',
				'  SMTP_PORT: Env.schema.number(),',
				'  SMTP_USERNAME: Env.schema.string(),',
				'  SMTP_PASSWORD: Env.schema.string(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the Sentry SDK',
				'  |----------------------------------------------------------',
				'  */',
				'  SENTRY_DSN: Env.schema.string(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the ally (OAuth) package',
				'  |----------------------------------------------------------',
				'  */',
				'  FACEBOOK_CLIENT_ID: Env.schema.string.optional(),',
				'  FACEBOOK_CLIENT_SECRET: Env.schema.string.optional(),',
				'  GITHUB_CLIENT_ID: Env.schema.string.optional(),',
				'  GITHUB_CLIENT_SECRET: Env.schema.string.optional(),',
				'  GOOGLE_CLIENT_ID: Env.schema.string.optional(),',
				'  GOOGLE_CLIENT_SECRET: Env.schema.string.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for Backup Configuration',
				'  |----------------------------------------------------------',
				'  */',
				"  BACKUP_STORAGE_DISK: Env.schema.enum.optional(['fs', 's3', 'r2', 'r2-backup'] as const),",
				'  BACKUP_TIME: Env.schema.string.optional(),',
				'  BACKUP_ENCRYPTION_ENABLED: Env.schema.boolean.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for Backup Configuration: Retention',
				'  |----------------------------------------------------------',
				'  */',
				'  BACKUP_RETENTION_DAILY: Env.schema.number.optional(),',
				'  BACKUP_RETENTION_WEEKLY: Env.schema.number.optional(),',
				'  BACKUP_RETENTION_MONTHLY: Env.schema.number.optional(),',
				'  BACKUP_RETENTION_YEARLY: Env.schema.number.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for Backup Configuration: Health Check',
				'  |----------------------------------------------------------',
				'  */',
				'  BACKUP_MAX_AGE_HOURS: Env.schema.number.optional(),',
				'  BACKUP_MAX_SIZE_MB: Env.schema.number.optional(),',
				'  BACKUP_MIN_FREE_SPACE_GB: Env.schema.number.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for Backup Configuration: Notifications',
				'  |----------------------------------------------------------',
				'  */',
				'  BACKUP_NOTIFICATION_EMAIL: Env.schema.string.optional(),',
				'  BACKUP_NOTIFY_SUCCESS: Env.schema.boolean.optional(),',
				'  BACKUP_NOTIFY_FAILURE: Env.schema.boolean.optional(),',
				'  BACKUP_NOTIFY_HEALTH_CHECK: Env.schema.boolean.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for Backup Configuration: Differential',
				'  |----------------------------------------------------------',
				'  */',
				'  BACKUP_EXCLUDED_TABLES: Env.schema.string.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the drive package',
				'  |----------------------------------------------------------',
				'  */',
				"  DRIVE_DISK: Env.schema.enum(['fs', 's3', 'r2'] as const),",
				'  AWS_ACCESS_KEY_ID: Env.schema.string.optional(),',
				'  AWS_SECRET_ACCESS_KEY: Env.schema.string.optional(),',
				'  AWS_REGION: Env.schema.string.optional(),',
				'  S3_BUCKET: Env.schema.string.optional(),',
				'  R2_KEY: Env.schema.string.optional(),',
				'  R2_SECRET: Env.schema.string.optional(),',
				'  R2_BUCKET: Env.schema.string.optional(),',
				'  R2_ENDPOINT: Env.schema.string.optional(),',
				'  R2_PUBLIC_URL: Env.schema.string.optional(),',
				'  /* Private R2 bucket for the backup system (no public custom domain) */',
				'  BACKUP_R2_BUCKET: Env.schema.string.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring file upload',
				'  |----------------------------------------------------------',
				'  */',
				'  MAX_UPLOAD_SIZE: Env.schema.number.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the limiter package',
				'  |----------------------------------------------------------',
				'  */',
				"  LIMITER_STORE: Env.schema.enum(['redis', 'memory'] as const),",
				'  API_RATE_LIMIT_DEFAULT: Env.schema.number.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for sitemap.xml generation.',
				'  | Comma-separated lists; both have safe defaults in config/sitemap.ts.',
				'  |----------------------------------------------------------',
				'  */',
				'  SITEMAP_ADDITIONS: Env.schema.string.optional(),',
				'  SITEMAP_EXCLUSIONS: Env.schema.string.optional(),',
				'})',
				'',
			].join('\n'),
		},

		// ─── .env.example — API-token-only template with CORS first-class ────
		{
			path: 'apps/web/.env.example',
			content: [
				'# Node',
				'TZ=UTC',
				'PORT=3333',
				'HOST=localhost',
				'NODE_ENV=development',
				'',
				'# App',
				'LOG_LEVEL=info',
				'APP_KEY=',
				'APP_URL=http://localhost:3333',
				'APP_NAME=AdonisJS Foundry',
				'',
				'# Session',
				'SESSION_DRIVER=redis',
				'',
				'# Auth guards — this flavor authenticates exclusively through API tokens.',
				'# AUTH_GUARD_WEB=false disables the session guard; the whole backend is driven',
				'# through /api/v1/* with Bearer tokens.',
				'AUTH_GUARD_WEB=false',
				'AUTH_GUARD_API=true',
				'# Default lifetime of issued API tokens (e.g. "30 days", "7d", "24h").',
				'AUTH_API_TOKEN_EXPIRY=30 days',
				'# Client-side callback URL for OAuth API mode (spec #6): after a provider',
				'# callback the backend issues an API token and redirects to this URL with',
				'# `?token=...&expires_at=...`. Leave empty to disable social login.',
				'AUTH_API_CLIENT_URL=',
				'',
				'# CORS — comma-separated allowlist of external front origins (your Next.js,',
				'# Nuxt, mobile bundle origin, ...). Empty = no cross-origin browser access.',
				'# This is the first config step when connecting a cross-origin front.',
				'CORS_ALLOWED_ORIGINS=',
				'',
				'# Database',
				'PG_HOST=127.0.0.1',
				'PG_PORT=5432',
				'PG_USER=user',
				'PG_PASSWORD=password',
				'PG_DB_NAME=app',
				'',
				'# Redis',
				'REDIS_HOST=127.0.0.1',
				'REDIS_PORT=6379',
				'REDIS_PASSWORD=',
				'REDIS_SOCKET=',
				'',
				'# Queue',
				'# redis: jobs are consumed by a separate worker (node ace queue:work).',
				'# sync: jobs run inline in the calling process (no worker, no Redis).',
				'QUEUE_DRIVER=redis',
				'# Redis connection used by the queue (see config/redis.ts).',
				'QUEUE_CONNECTION=local',
				'# Worker settings.',
				'QUEUE_CONCURRENCY=5',
				'QUEUE_MAX_RETRIES=3',
				'# Scheduled maintenance tasks (see config/maintenance.ts). Each value is a',
				'# duration string ("1d", "24h", "30m"); "0" disables the task. Unset values',
				'# fall back to a daily schedule.',
				'MAINTENANCE_LOG_PRUNE_SCHEDULE=',
				'MAINTENANCE_BACKUP_RETENTION_SCHEDULE=',
				'# Retention window in days for Log Entry pruning (default 180).',
				'LOG_RETENTION_DAYS=',
				'',
				'# Mail',
				'MAIL_MAILER=smtp',
				'MAIL_FROM_NAME=${APP_NAME}',
				'MAIL_FROM_ADDRESS=contact@example.com',
				'',
				'# SMTP',
				'SMTP_HOST=localhost',
				'SMTP_PORT=1025',
				'SMTP_USERNAME=username',
				'SMTP_PASSWORD=password',
				'',
				'# Sentry',
				'SENTRY_DSN=<your_dsn_url>',
				'',
				'# Oauth',
				'FACEBOOK_CLIENT_ID=',
				'FACEBOOK_CLIENT_SECRET=',
				'GITHUB_CLIENT_ID=',
				'GITHUB_CLIENT_SECRET=',
				'GOOGLE_CLIENT_ID=',
				'GOOGLE_CLIENT_SECRET=',
				'DRIVE_DISK=fs',
				'AWS_ACCESS_KEY_ID=',
				'AWS_SECRET_ACCESS_KEY=',
				'AWS_REGION=',
				'S3_BUCKET=',
				'R2_KEY=',
				'R2_SECRET=',
				'R2_BUCKET=',
				'R2_ENDPOINT=',
				'R2_PUBLIC_URL=',
				'# Private R2 bucket for the backup system (no public custom domain).',
				'# Used by the r2-backup disk when BACKUP_STORAGE_DISK=r2-backup.',
				'BACKUP_R2_BUCKET=',
				'LIMITER_STORE=redis',
				'# Default per-client API rate limit (requests/minute) when a user has no custom limit',
				'API_RATE_LIMIT_DEFAULT=60',
				'',
			].join('\n'),
		},

		// ─── adonisrc.ts — drop the Inertia/Vite providers and asset hooks ───
		{
			path: 'apps/web/adonisrc.ts',
			content: [
				"import { indexEntities } from '@adonisjs/core'",
				"import { defineConfig } from '@adonisjs/core/app'",
				"import { generateRegistry } from '@tuyau/core/hooks'",
				"import { restRoutesRegistryHook } from '#transport/core/rest/rest_routes_registry_hook'",
				'',
				'export default defineConfig({',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Experimental flags',
				'  |--------------------------------------------------------------------------',
				'  |',
				'  | The following features will be enabled by default in the next major',
				'  | release of AdonisJS. You can opt into them today to avoid any breaking',
				'  | changes during upgrade.',
				'  |',
				'  */',
				'  experimental: {},',
				'',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Commands',
				'  |--------------------------------------------------------------------------',
				'  |',
				'  | List of ace commands to register from packages. The application',
				'  | commands will be scanned automatically from the "./commands" directory.',
				'  |',
				'  */',
				'  commands: [',
				"    () => import('@adonisjs/core/commands'),",
				"    () => import('@adonisjs/lucid/commands'),",
				"    () => import('@adonisjs/session/commands'),",
				"    () => import('@adonisjs/mail/commands'),",
				"    () => import('@adonisjs/queue/commands'),",
				'  ],',
				'',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Service providers',
				'  |--------------------------------------------------------------------------',
				'  |',
				'  | List of service providers to import and register when booting the',
				'  | application',
				'  |',
				'  | The `api` flavor is headless and CMS-less: the Inertia, Vite and',
				'  | Transmit providers are all gone.',
				'  |',
				'  */',
				'  providers: [',
				"    () => import('@adonisjs/core/providers/app_provider'),",
				"    () => import('@adonisjs/core/providers/hash_provider'),",
				'    {',
				"      file: () => import('@adonisjs/core/providers/repl_provider'),",
				"      environment: ['repl', 'test'],",
				'    },',
				"    () => import('@adonisjs/core/providers/vinejs_provider'),",
				"    () => import('@adonisjs/core/providers/edge_provider'),",
				"    () => import('@adonisjs/session/session_provider'),",
				"    () => import('@adonisjs/shield/shield_provider'),",
				"    () => import('@adonisjs/static/static_provider'),",
				"    () => import('@adonisjs/lucid/database_provider'),",
				"    () => import('@adonisjs/cors/cors_provider'),",
				"    () => import('@adonisjs/auth/auth_provider'),",
				"    () => import('#providers/api_provider'),",
				"    () => import('@adonisjs/redis/redis_provider'),",
				"    () => import('@adonisjs/queue/queue_provider'),",
				"    () => import('#providers/sentry_provider'),",
				"    () => import('@adonisjs/i18n/i18n_provider'),",
				"    () => import('@adonisjs/ally/ally_provider'),",
				"    () => import('@adonisjs/mail/mail_provider'),",
				"    () => import('@adonisjs/drive/drive_provider'),",
				"    () => import('@adonisjs/limiter/limiter_provider'),",
				'  ],',
				'',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Preloads',
				'  |--------------------------------------------------------------------------',
				'  |',
				'  | List of modules to import before starting the application.',
				'  |',
				'  */',
				'  preloads: [',
				"    () => import('#start/routes'),",
				"    () => import('#start/kernel'),",
				"    () => import('#start/validator'),",
				"    () => import('#start/events'),",
				"    () => import('#start/container'),",
				"    () => import('#start/dashboard'),",
				"    () => import('#start/sitemap'),",
				"    () => import('#start/nav'),",
				"    () => import('#start/extensions'),",
				"    () => import('#start/scheduler'),",
				'  ],',
				'',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Tests',
				'  |--------------------------------------------------------------------------',
				'  |',
				'  | List of test suites to organize tests by their type. Feel free to',
				'  | remove and add additional suites.',
				'  |',
				'  */',
				'  tests: {',
				'    suites: [',
				'      {',
				"        files: ['tests/unit/**/*.spec.{ts,js}'],",
				"        name: 'unit',",
				'        timeout: 2000,',
				'      },',
				'      {',
				"        files: ['tests/integration/**/*.spec.{ts,js}'],",
				"        name: 'integration',",
				'        timeout: 5000,',
				'      },',
				'      {',
				"        files: ['tests/functional/**/*.spec.{ts,js}'],",
				"        name: 'functional',",
				'        timeout: 30000,',
				'      },',
				'    ],',
				'    forceExit: false,',
				'  },',
				'',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Metafiles',
				'  |--------------------------------------------------------------------------',
				'  |',
				'  | A collection of files you want to copy to the build folder when',
				'  | creating the production build.',
				'  |',
				'  */',
				'  metaFiles: [',
				'    {',
				"      pattern: 'resources/views/**/*.edge',",
				'      reloadServer: false,',
				'    },',
				'    {',
				"      pattern: 'public/**',",
				'      reloadServer: false,',
				'    },',
				'    {',
				"      pattern: 'resources/lang/**/*.{json,yaml,yml}',",
				'      reloadServer: false,',
				'    },',
				'  ],',
				'',
				'  hooks: {',
				'    init: [',
				'      indexEntities({',
				'        transformers: {',
				'          enabled: true,',
				'          withSharedProps: false,',
				"          source: 'app',",
				"          importAlias: '#transport',",
				"          glob: ['**\\/*transformer.ts'],",
				'        },',
				'        controllers: {',
				'          enabled: true,',
				"          source: 'app',",
				"          importAlias: '#transport',",
				"          glob: ['**\\/*_controller.ts'],",
				'        },',
				'      }),',
				'      generateRegistry(),',
				'      restRoutesRegistryHook(),',
				'    ],',
				'  },',
				'})',
				'',
			].join('\n'),
		},

		// ─── package.json (root) — monorepo scripts, single typecheck target ────
		// The `workspaces` glob field is flavor-invariant: it stays identical to
		// main's even though the design-system package is deleted wholesale,
		// because a glob matching nothing is valid. Narrowing it would make the
		// root rewrite diverge from main for no install benefit.
		// The `@adonisjs/ally` overrides block of main's root manifest is
		// deliberately absent here: without it, a fresh `npm install` would
		// auto-resolve the package's peer dependency on
		// `@adonisjs/inertia@^4.2.0`. The drop is only safe because the flavor
		// branch keeps main's superset lockfile and installs with `npm ci`
		// (no re-resolution), so the peer stays resolved from the lockfile.
		{
			path: 'package.json',
			content: [
				'{',
				'  "name": "adonisjs-foundry",',
				'  "version": "2.1.0",',
				'  "private": true,',
				'  "license": "UNLICENSED",',
				'  "type": "module",',
				'  "workspaces": [',
				'    "apps/*",',
				'    "packages/*"',
				'  ],',
				'  "scripts": {',
				'    "start": "npm run start --workspace @foundry/web",',
				'    "dev": "npm run dev --workspace @foundry/web",',
				'    "build": "npm run build --workspace @foundry/web",',
				'    "test": "npm run test --workspace @foundry/web",',
				'    "docker:up": "docker compose up -d",',
				'    "docker:stop": "docker compose stop -d",',
				'    "lint": "oxlint",',
				'    "lint:ci": "oxlint",',
				'    "lint:fix": "oxlint --fix",',
				'    "format": "oxfmt --write .",',
				'    "format:ci": "oxfmt --check .",',
				'    "format:check": "oxfmt --check .",',
				'    "typecheck": "tsc --noEmit -p apps/web/tsconfig.json",',
				'    "postinstall": "patch-package"',
				'  },',
				'  "devDependencies": {',
				'    "oxfmt": "^0.70.0",',
				'    "oxlint": "^1.85.0",',
				'    "typescript": "~5.9.3"',
				'  },',
				'  "engines": {',
				'    "node": ">=24.0.0"',
				'  }',
				'}',
				'',
			].join('\n'),
		},

		// ─── tsconfig.json — drop the Inertia project reference ──────────────
		{
			path: 'apps/web/tsconfig.json',
			content: [
				'{',
				'  "extends": "@adonisjs/tsconfig/tsconfig.app.json",',
				'  "compilerOptions": {',
				'    "rootDir": "./",',
				'  "outDir": "./build"',
				'  }',
				'}',
				'',
			].join('\n'),
		},

		// ─── apps/web/package.json — drop the front script + the prune alias ───
		{
			path: 'apps/web/package.json',
			content: [
				'{',
				'  "name": "@foundry/web",',
				'  "version": "2.1.0",',
				'  "private": true,',
				'  "license": "UNLICENSED",',
				'  "type": "module",',
				'  "imports": {',
				'    "#transport/*": "./app/*.js",',
				'    "#generated/*": "./.adonisjs/server/*.js",',
				'    "#types/*": "./types/*.js",',
				'    "#providers/*": "./providers/*.js",',
				'    "#database/*": "./database/*.js",',
				'    "#factories/*": "./database/factories/*.js",',
				'    "#shared/*": "./src/shared/*.js",',
				'    "#core/*": "./src/core/*.js",',
				'    "#identity/*": "./src/identity/*.js",',
				'    "#auth/*": "./src/auth/*.js",',
				'    "#account/*": "./src/account/*.js",',
				'    "#file/*": "./src/file/*.js",',
				'    "#log/*": "./src/log/*.js",',
				'    "#backup/*": "./src/backup/*.js",',
				'    "#webhook/*": "./src/webhook/*.js",',
				'    "#tests/*": "./tests/*.js",',
				'    "#start/*": "./start/*.js",',
				'    "#config/*": "./config/*.js"',
				'  },',
				'  "scripts": {',
				'    "start": "node bin/server.js",',
				'    "build": "node ace build",',
				'    "dev": "node ace serve --hmr",',
				'    "test": "node ace test"',
				'  },',
				'  "dependencies": {',
				'    "@adonisjs/ally": "^6.0.0",',
				'    "@adonisjs/auth": "^10.0.0",',
				'    "@adonisjs/core": "^7.0.0",',
				'    "@adonisjs/cors": "^3.0.0",',
				'    "@adonisjs/drive": "^4.0.0",',
				'    "@adonisjs/i18n": "^3.0.0",',
				'    "@adonisjs/inertia": "^5.0.0",',
				'    "@adonisjs/limiter": "^3.0.1",',
				'    "@adonisjs/lucid": "^22.0.0",',
				'    "@adonisjs/mail": "^10.0.0",',
				'    "@adonisjs/queue": "0.6.2",',
				'    "@adonisjs/redis": "^10.0.1",',
				'    "@adonisjs/session": "^8.0.0",',
				'    "@adonisjs/shield": "^9.0.0",',
				'    "@adonisjs/static": "^2.0.0",',
				'    "@adonisjs/transmit": "^3.0.2",',
				'    "@adonisjs/transmit-client": "^1.1.0",',
				'    "@adonisjs/vite": "^6.0.2",',
				'    "@aws-sdk/client-s3": "^3.1137.0",',
				'    "@aws-sdk/s3-request-presigner": "^3.1137.0",',
				'    "@fontsource/cormorant-garamond": "^5.2.11",',
				'    "@fontsource/jost": "^5.3.0",',
				'    "@fontsource/playfair-display": "^5.3.0",',
				'    "@foundry/design-system": "^2.1.0",',
				'    "@iconify/react": "^6.0.2",',
				'    "@inertiajs/react": "^3.7.1",',
				'    "@lukeed/ms": "^2.0.2",',
				'    "@sentry/node": "^10.75.2",',
				'    "@tailwindcss/vite": "^4.2.1",',
				'    "@tuyau/core": "^1.0.0",',
				'    "@vinejs/vine": "^4.3.0",',
				'    "better-sqlite3": "^13.0.3",',
				'    "dompurify": "^3.4.16",',
				'    "edge.js": "^6.5.1",',
				'    "html-to-image": "^1.11.13",',
				'    "ipaddr.js": "^2.4.0",',
				'    "jsdom": "^30.1.1",',
				'    "luxon": "^3.7.2",',
				'    "patch-package": "^8.0.1",',
				'    "pg": "^8.22.0",',
				'    "react": "^19.3.0",',
				'    "react-dom": "^19.3.0",',
				'    "react-markdown": "^10.1.0",',
				'    "reflect-metadata": "^0.2.2",',
				'    "rehype-raw": "^7.0.0",',
				'    "sharp": "^0.35.4",',
				'    "sinon": "^22.1.0",',
				'    "sonner": "^2.0.7",',
				'    "tailwindcss": "^4.3.3",',
				'    "uuid": "^14.0.1"',
				'  },',
				'  "devDependencies": {',
				'    "@adonisjs/assembler": "^8.5.1",',
				'    "@adonisjs/tsconfig": "^2.0.0",',
				'    "@japa/api-client": "^3.2.1",',
				'    "@japa/assert": "^4.2.0",',
				'    "@japa/plugin-adonisjs": "^5.1.0",',
				'    "@japa/runner": "^5.3.0",',
				'    "@poppinss/ts-exec": "^1.4.4",',
				'    "@types/dompurify": "^3.2.0",',
				'    "@types/jsdom": "^30.0.0",',
				'    "@types/luxon": "^3.7.5",',
				'    "@types/node": "~26.6.2",',
				'    "@types/react": "^19.3.0",',
				'    "@types/react-dom": "^19.3.0",',
				'    "@types/sinon": "^22.0.0",',
				'    "@vitejs/plugin-react": "^6.1.1",',
				'    "hot-hook": "^1.0.0",',
				'    "pino-pretty": "^13.1.3",',
				'    "vite": "^8.3.0",',
				'    "vitest": "^5.0.0",',
				'    "youch": "^4.1.0"',
				'  },',
				'  "engines": {',
				'    "node": ">=24.0.0"',
				'  },',
				'  "hotHook": {',
				'    "boundaries": [',
				'      "./app/**/controllers/**/*.ts",',
				'      "./app/**/middleware/**/*.ts",',
				'      "./app/**/rest/**/*.ts"',
				'    ]',
				'  }',
				'}',
				'',
			].join('\n'),
		},

		// ─── README.md — flavor-specific surface documentation ───────────────
		{
			path: 'README.md',
			content: [
				'# AdonisJS Foundry — `api` flavor',
				'',
				'A production-ready AdonisJS v7 backend exposed as a pure versioned REST API — no Inertia, no React, no admin UI, no public site, no CMS. Every backend capability reaches your external front (Next.js, Nuxt, a mobile app) through `/api/v1/*` behind API token authentication.',
				'',
				'## What is included',
				'',
				'- **Versioned REST API** — identity/token auth (`/api/v1/auth`), profile and account (`/api/v1/profile`, `/api/v1/account`) and the admin surface (`/api/v1/admin`) for users, roles, permissions, files, folders, dashboard, logs and maintenance.',
				'- **API token authentication** — opaque Bearer tokens issued by `/api/v1/auth/login` (and `/register`). No cookies, no CSRF handling on the token-guarded surface.',
				'- **File management** — upload, folders, multi-disk storage (local, S3, R2) and public file serving through drive.',
				'- **Operational features** — Redis cache/locks, mail, i18n, rate limiting, audit logs, maintenance mode and a first-class CORS policy.',
				'',
				'No view layer and no CMS ship in this repository: the Inertia/React/Vite stack and the page/template/builder module live on `main` only. You bring the front, and it consumes the API.',
				'',
				'## Quick start',
				'',
				'```bash',
				'npm install',
				'cp .env.example .env',
				'node ace generate:key',
				'node ace migration:run',
				'npm run dev',
				'```',
				'',
				'The API is available at `http://localhost:3333/api/v1`.',
				'',
				'## Authentication flow',
				'',
				'1. `POST /api/v1/auth/login` with `email` + `password` returns the user payload and an API token.',
				'2. Send the token in the `Authorization: Bearer <token>` header on every authenticated request.',
				'3. `POST /api/v1/auth/logout` revokes the token; token lifetime is configured with `AUTH_API_TOKEN_EXPIRY` (default `30 days`).',
				'',
				'Registration, email verification, password reset and invitation acceptance are `POST /api/v1/auth/*` endpoints. The authenticated identity, profile and account endpoints live at `/api/v1/profile` and `/api/v1/account`.',
				'',
				'## Social login (OAuth API mode)',
				'',
				'OAuth providers (GitHub, Google, Facebook) work headless: open `/oauth/{provider}` in a browser or webview, and after the provider callback the backend issues an API token and redirects to `AUTH_API_CLIENT_URL` with `?token=...&expires_at=...`. Your mobile app reads the token from the redirect and uses it as a Bearer token from then on. With `AUTH_API_CLIENT_URL` unset, the `/oauth/*` callback returns a 500 config error rather than a session.',
				'',
				'## Admin surface (endpoint map)',
				'',
				'Under `/api/v1/admin`, each resource is a thin controller reusing the shared domain layer — administrators are just API claimers, and the surface is exactly the non-CMS one built on `main` (#6/#7):',
				'',
				'| Resource    | Endpoints                                                                                      |',
				'| ----------- | ---------------------------------------------------------------------------------------------- |',
				'| Users       | `GET/POST /users`, `GET/PUT/DELETE /users/:id`                                                 |',
				'| Roles       | `GET/POST /roles`, `GET/PUT/DELETE /roles/:id`                                                 |',
				'| Permissions | `GET /permissions`                                                                             |',
				'| Files       | `GET/POST /files`, `GET/DELETE /files/:id`, `PUT /files/:id/move`, `PUT/DELETE /files/:id/alt` |',
				'| Folders     | `GET/POST /folders`, `GET/PUT/DELETE /folders/:id`                                             |',
				'| Dashboard   | `GET /dashboard`                                                                               |',
				'| Logs        | `GET /logs`                                                                                    |',
				'| Maintenance | `GET/PUT /maintenance`, `PUT /maintenance/toggle`                                              |',
				'',
				'All of them require `Authorization: Bearer <token>` and enforce the usual permission middleware (`users.view`, `files.create`, ...).',
				'',
				'## CORS',
				'',
				'The REST API is consumed cross-origin by definition, so CORS is a config step, not a code change: set `CORS_ALLOWED_ORIGINS` in `.env` to a comma-separated list of your front origins',
				'',
				'```',
				'CORS_ALLOWED_ORIGINS=https://app.example.com,http://localhost:3000',
				'```',
				'',
				'Empty (the default) allows no cross-origin browser access.',
				'',
				'## Security headers',
				'',
				'The CSP and other security headers (shield) stay intact. External fronts connect through the API with Bearer tokens, and no CSRF cookie is involved on the token-guarded `/api/v1/*` surface.',
				'',
				'## Upgrade path to `full`',
				'',
				'Choosing this flavor is not a one-way door. See `docs/flavors/api/upgrade-to-full.md` for the documented manual path to recover the Inertia admin, the public site, the frontend tooling and the CMS.',
				'',
				'## Available scripts',
				'',
				'| Script              | Description                   |',
				'| ------------------- | ----------------------------- |',
				'| `npm run dev`       | Start the dev server with HMR |',
				'| `npm run build`     | Build for production          |',
				'| `npm start`         | Start the production server   |',
				'| `npm test`          | Run the backend test suite    |',
				'| `npm run lint`      | Run oxlint                    |',
				'| `npm run format`    | Format code with oxfmt        |',
				'| `npm run typecheck` | Type-check the backend        |',
				'',
			].join('\n'),
		},
	],

	dependencies: [
		{
			file: 'apps/web/package.json',
			packages: [
				// Frontend runtime
				'@adonisjs/inertia',
				'@adonisjs/vite',
				'@inertiajs/react',
				'@foundry/design-system',
				'react',
				'react-dom',
				'sonner',
				'html-to-image',
				'@iconify/react',
				'@fontsource/cormorant-garamond',
				'@fontsource/jost',
				'@fontsource/playfair-display',
				'tailwindcss',
				'@tailwindcss/vite',
				'react-markdown',
				'rehype-raw',
				// Frontend tooling
				'@vitejs/plugin-react',
				'vite',
				'vitest',
				'@types/react',
				'@types/react-dom',
				// CMS/real-time (main-only)
				'@adonisjs/transmit',
				'@adonisjs/transmit-client',
			],
		},
	],
};

export default apiManifest;
