/**
 * `inertia` flavor manifest.
 *
 * Derives the hand-written-Inertia flavor from `main`: keeps the full admin
 * back-office (users, roles, permissions, files, logs, maintenance, settings,
 * dashboard) and the complete auth flow, prunes the `page` and `template`
 * domains and Transmit entirely, and ships a minimal hand-written front
 * (a blank home page and error pages, each served by its own `core.*`
 * controller).
 *
 * The delete inventory mirrors ADR-0001's CMS delete map: the co-located CMS
 * units (the `src/cms` business layer, the `app/cms` transport layer, CMS
 * migrations/seeders/factories, the `resources/lang/{en,fr}/cms` i18n
 * namespaces, the contact email template, the CMS React subtrees, the CMS
 * test suites and the CMS ace command), plus the Transmit integration.
 * The rewrites drop the CMS and Transmit registrations from the allowlisted
 * composition files and turn the `cms` feature flag off.
 *
 * Applied by {@link '../engine'} via
 * `node --import @poppinss/ts-exec tooling/prune/apply.ts inertia`.
 */
import type { FlavorManifest } from '#prune/types';

const inertiaManifest: FlavorManifest = {
	flavor: 'inertia',

	delete: [
		// ─── CMS business layer (actions, services, repositories, models) ──────
		'apps/web/src/cms',

		// ─── CMS transport layer (controllers, routes, nav, helpers, REST) ─────
		'apps/web/app/cms',

		// ─── CMS migrations ─────────────────────────────────────────────────────
		'apps/web/database/migrations/cms',

		// ─── CMS seeders ────────────────────────────────────────────────────────
		'apps/web/database/seeders/cms',

		// ─── CMS factories ──────────────────────────────────────────────────────
		'apps/web/database/factories/cms',

		// ─── CMS i18n namespaces (page, template, builder) ──────────────────────
		'apps/web/resources/lang/en/cms',
		'apps/web/resources/lang/fr/cms',

		// ─── CMS email template (contact form) ──────────────────────────────────
		'apps/web/resources/views/emails/contact_form_email.edge',

		// ─── CMS React subtrees (builder, renderer, pages) ──────────────────────
		'apps/web/inertia/pages/cms',
		'apps/web/inertia/components/cms',

		// ─── CMS test suites ────────────────────────────────────────────────────
		'apps/web/tests/unit/cms',
		'apps/web/tests/integration/cms',
		'apps/web/tests/functional/cms',
		'apps/web/tests/helpers/page_search.ts',

		// ─── Cross-domain OpenAPI functional tests (import the pruned CMS api_docs) ──
		'apps/web/tests/functional/core/openapi_docs.spec.ts',
		'apps/web/tests/functional/core/openapi_rollout.spec.ts',

		// ─── CMS ace command ────────────────────────────────────────────────────
		'apps/web/commands/cms_normalize_migration_names.ts',

		// ─── Transmit integration + CMS feature config ──────────────────────────
		'apps/web/start/transmit.ts',
		'apps/web/config/transmit.ts',
		'apps/web/config/cms.ts',

		// ─── Inbound webhook module (main-only) ─────────────────────────────────
		'apps/web/src/webhook',
		'apps/web/app/webhook',
		'apps/web/config/webhooks.ts',
		'apps/web/database/migrations/webhook',
		'apps/web/database/factories/webhook',
		'apps/web/inertia/pages/webhook',
		'apps/web/resources/lang/en/webhook.json',
		'apps/web/resources/lang/fr/webhook.json',
		'apps/web/tests/unit/webhook',
		'apps/web/tests/integration/webhook',
		'apps/web/tests/functional/webhook',

		// ─── Prune pipeline (main-only infrastructure) ──────────────────────────
		'tooling/prune',
		'apps/web/tests/unit/prune',

		// ─── Generated indexes ──────────────────────────────────────────────────
		// The entire .adonisjs directory is deleted so the pruned tree carries
		// zero CMS references. `npm run dev` regenerates it fresh against the
		// pruned source tree (init hooks + ready hook + Tuyau routesScanned).
		'apps/web/.adonisjs',
	],

	rewrites: [
		// ─── config/features.ts — turn the cms flag off ─────────────────────────
		{
			path: 'apps/web/config/features.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Feature flags',
				'|--------------------------------------------------------------------------',
				'|',
				'| Runtime toggles to enable or disable route modules.',
				'| All features are enabled by default — change a boolean to',
				'| deactivate a module at runtime without touching routing code.',
				'|',
				'| The `inertia` flavor drops the CMS module (page/template/builder): the',
				'| `cms` flag is off and the CMS route registrations are absent from',
				'| `start/routes.ts`.',
				'*/',
				'',
				'export default {',
				'  auth: true,',
				'  settings: true,',
				'  admin: true,',
				'  adminApi: true,',
				'  apiDocs: true,',
				'  cms: false,',
				'  maintenance: true,',
				'} as const',
				'',
			].join('\n'),
		},

		// ─── config/database.ts — drop the CMS migration folder ─────────────────
		{
			path: 'apps/web/config/database.ts',
			content: [
				"import app from '@adonisjs/core/services/app'",
				"import { defineConfig } from '@adonisjs/lucid'",
				'',
				'const dbConfig = defineConfig({',
				'  /**',
				'   * Default connection used for all queries.',
				'   */',
				"  connection: 'pg',",
				'',
				'  connections: {',
				'    /**',
				'     * SQLite connection (default).',
				'     */',
				'    sqlite: {',
				"      client: 'better-sqlite3',",
				'',
				'      connection: {',
				'        /**',
				'         * Database file location.',
				'         */',
				"        filename: app.tmpPath('db.sqlite3'),",
				'      },',
				'',
				'      /**',
				'       * Required by Knex for SQLite defaults.',
				'       */',
				'      useNullAsDefault: true,',
				'',
				'      migrations: {',
				'        /**',
				'         * Sort migration files naturally by filename.',
				'         */',
				'        naturalSort: true,',
				'',
				'        /**',
				'         * Paths containing migration files. The `inertia` flavor prunes the',
				'         * CMS module, so `database/migrations/cms` is absent.',
				'         */',
				"        paths: ['database/migrations'],",
				'      },',
				'    },',
				'',
				'    /**',
				'     * PostgreSQL connection.',
				'     * Install package to switch: npm install pg',
				'     */',
				'    pg: {',
				"      client: 'pg',",
				'      connection: {',
				'        host: process.env.PG_HOST,',
				'        port: Number(process.env.PG_PORT || 5432),',
				'        user: process.env.PG_USER,',
				'        password: process.env.PG_PASSWORD,',
				'        database: process.env.PG_DB_NAME,',
				'      },',
				'      migrations: {',
				'        naturalSort: true,',
				"        paths: ['database/migrations'],",
				'      },',
				'      debug: app.inDev,',
				'    },',
				'',
				'    /**',
				'     * MySQL / MariaDB connection.',
				'     * Install package to switch: npm install mysql2',
				'     */',
				'    // mysql: {',
				'    //   client: "mysql2",',
				'    //   connection: {',
				'    //     host: process.env.MYSQL_HOST,',
				'    //     port: Number(process.env.MYSQL_PORT || 3306),',
				'    //     user: process.env.MYSQL_USER,',
				'    //     password: process.env.MYSQL_PASSWORD,',
				'    //     database: process.env.MYSQL_DB_NAME,',
				'    //   },',
				'    //   migrations: {',
				'    //     naturalSort: true,',
				'    //     paths: ["database/migrations"],',
				'    //   },',
				'    //   debug: app.inDev,',
				'    // },',
				'',
				'    /**',
				'     * Microsoft SQL Server connection.',
				'     * Install package to switch: npm install tedious',
				'     */',
				'    // mssql: {',
				'    //   client: "mssql",',
				'    //   connection: {',
				'    //     server: process.env.MSSQL_SERVER,',
				'    //     port: Number(process.env.MSSQL_PORT || 1433),',
				'    //     user: process.env.MSSQL_USER,',
				'    //     password: process.env.MSSQL_PASSWORD,',
				'    //     database: process.env.MSSQL_DB_NAME,',
				'    //   },',
				'    //   migrations: {',
				'    //     naturalSort: true,',
				'    //     paths: ["database/migrations"],',
				'    //   },',
				'    //   debug: app.inDev,',
				'    // },',
				'',
				'    /**',
				'     * libSQL (Turso) connection.',
				'     * Install package to switch: npm install @libsql/client',
				'     */',
				'    // libsql: {',
				'    //   client: "libsql",',
				'    //   connection: {',
				'    //     url: process.env.LIBSQL_URL,',
				'    //     authToken: process.env.LIBSQL_AUTH_TOKEN,',
				'    //   },',
				'    //   useNullAsDefault: true,',
				'    //   migrations: {',
				'    //     naturalSort: true,',
				'    //     paths: ["database/migrations"],',
				'    //   },',
				'    //   debug: app.inDev,',
				'    // },',
				'  },',
				'})',
				'',
				'export default dbConfig',
				'',
			].join('\n'),
		},

		// ─── config/shield.ts — drop the CMS iframe frame-src hosts ─────────────
		{
			path: 'apps/web/config/shield.ts',
			content: [
				"import app from '@adonisjs/core/services/app'",
				"import { defineConfig } from '@adonisjs/shield'",
				'',
				'/**',
				' * CSP configuration for the `inertia` flavor.',
				' *',
				' * The CMS `iframe` block (and its `frame-src` host allowlist) is pruned in',
				' * this flavor, so the CMS-specific imports are gone and the `frame-src`',
				' * directive falls back to the default origin-only policy.',
				' */',
				'const shieldConfig = defineConfig({',
				'  /**',
				'   * Configure CSP policies for your app. Refer documentation',
				'   * to learn more.',
				'   */',
				'  csp: {',
				'    /**',
				'     * Enable the Content-Security-Policy header.',
				'     */',
				'    enabled: true,',
				'',
				'    /**',
				'     * Report violations without blocking resources in dev/test.',
				'     * Enforce in production.',
				'     */',
				'    reportOnly: app.inDev || app.inTest,',
				'',
				'    /**',
				'     * Per-resource CSP directives.',
				'     */',
				'    directives: {',
				'      // Default: only same-origin',
				'      defaultSrc: ["\'self\'"],',
				'',
				'      // Scripts: self + Vite HMR in dev/test',
				'      scriptSrc: [',
				'        "\'self\'",',
				'        ...(app.inDev || app.inTest ? ["\'unsafe-eval\'", "\'unsafe-inline\'"] : []), // Vite HMR needs these in dev/test',
				'      ],',
				'',
				'      // Styles: self + Tailwind JIT inline styles',
				'      styleSrc: ["\'self\'", "\'unsafe-inline\'"],',
				'',
				'      // Images: self + data: URIs + HTTPS',
				"      imgSrc: [\"'self'\", 'data:', 'https:'],",
				'',
				'      // Fonts: self + data: (for inline fonts)',
				"      fontSrc: [\"'self'\", 'data:'],",
				'',
				'      // Connect: self + SSE + Vite HMR websocket + Sentry',
				'      connectSrc: [',
				'        "\'self\'",',
				"        ...(app.inDev || app.inTest ? ['ws:', 'wss:'] : []), // Vite HMR websocket",
				"        'https://*.sentry.io', // Sentry error reporting",
				'      ],',
				'',
				'      // Frames: default to same-origin only — the CMS iframe block is pruned.',
				'      frameSrc: ["\'self\'"],',
				'',
				'      // Frames: deny (xFrame also set to SAMEORIGIN)',
				'      frameAncestors: ["\'none\'"],',
				'',
				'      // Forms: self only',
				'      formAction: ["\'self\'"],',
				'',
				'      // Base URI: self',
				'      baseUri: ["\'self\'"],',
				'',
				'      // Object/embed: none',
				'      objectSrc: ["\'none\'"],',
				'',
				'      // Media: self + external direct video files (video block)',
				"      mediaSrc: [\"'self'\", 'https:'],",
				'',
				'      // Workers: self',
				'      workerSrc: ["\'self\'"],',
				'',
				'      // Manifest: self',
				'      manifestSrc: ["\'self\'"],',
				'    },',
				'  },',
				'',
				'  /**',
				'   * Configure CSRF protection options. Refer documentation',
				'   * to learn more.',
				'   */',
				'  csrf: {',
				'    /**',
				'     * Enable CSRF token verification for state-changing requests.',
				'     */',
				'    enabled: true,',
				'',
				'    /**',
				'     * Routes to exclude from CSRF checks. Useful for external webhooks or',
				'     * API endpoints. Patterns match `ctx.route.pattern` exactly (no glob),',
				'     * hence the function form.',
				'     *',
				'     * `/api/v1/*` is the token-guarded REST API: Bearer-token requests carry',
				'     * no cookies, so they are not exposed to CSRF. Session-authenticated API',
				'     * routes (`/api/admin/*`, `/api/settings/*`) keep full CSRF protection.',
				'     */',
				'    exceptRoutes: (ctx) =>',
				"      ctx.route !== undefined && ctx.route.pattern.replace(/^\\//, '').startsWith('api/v1/'),",
				'',
				'    /**',
				'     * Expose an encrypted XSRF-TOKEN cookie for frontend HTTP clients.',
				'     */',
				'    enableXsrfCookie: true,',
				'',
				'    /**',
				'     * HTTP methods protected by CSRF validation.',
				'     */',
				"    methods: ['POST', 'PUT', 'PATCH', 'DELETE'],",
				'  },',
				'',
				'  /**',
				'   * Control how your website should be embedded inside',
				'   * iframes.',
				'   */',
				'  xFrame: {',
				'    /**',
				'     * Enable the X-Frame-Options header.',
				'     */',
				'    enabled: true,',
				'',
				'    /**',
				'     * Block all framing attempts. Default value is DENY.',
				'     */',
				"    action: 'SAMEORIGIN',",
				'  },',
				'',
				'  /**',
				'   * Force browser to always use HTTPS.',
				'   */',
				'  hsts: {',
				'    /**',
				'     * Enable the Strict-Transport-Security header.',
				'     */',
				'    enabled: true,',
				'',
				'    /**',
				'     * HSTS policy duration remembered by browsers.',
				'     */',
				"    maxAge: '180 days',",
				'  },',
				'',
				'  /**',
				'   * Disable browsers from sniffing content types and rely only',
				'   * on the response content-type header.',
				'   */',
				'  contentTypeSniffing: {',
				'    /**',
				'     * Enable X-Content-Type-Options: nosniff.',
				'     */',
				'    enabled: true,',
				'  },',
				'})',
				'',
				'export default shieldConfig',
				'',
			].join('\n'),
		},

		// ─── start/routes.ts — drop the CMS, register the core home ────────────
		{
			path: 'apps/web/start/routes.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Routes file',
				'|--------------------------------------------------------------------------',
				'|',
				'| Route module index — each domain registers its own routes.',
				'| Feature flags in config/features.ts gate each module at runtime.',
				'|',
				'| The `inertia` flavor ships a hand-written front: the core home route is',
				'| registered here (it is dead on `main`, where the CMS page home serves',
				'| the site root), alongside the self-registering core surfaces (SEO,',
				'| admin, API) and the admin back-office.',
				'*/',
				'',
				'// Auth, identity, account, file, log and core routes self-register on import (feature-gated inside the modules).',
				"import '#transport/account/routes'",
				"import '#transport/auth/routes'",
				"import '#transport/file/routes'",
				"import '#transport/identity/routes'",
				"import '#transport/log/routes'",
				"import router from '@adonisjs/core/services/router'",
				"import features from '#config/features'",
				"import { registerCoreHealthRoutes } from '#transport/core/health.routes'",
				"import { registerCoreHomeRoute } from '#transport/core/routes'",
				"import { middleware } from '#start/kernel'",
				'',
				'// Health routes are outside maintenance middleware (liveness/readiness probes)',
				'registerCoreHealthRoutes()',
				'',
				'// Wrap all feature routes with maintenance middleware',
				'// Health routes are registered separately above (outside this wrapper)',
				'',
				'router',
				'  .group(() => {',
				'    // Hand-written front (home + error pages) — replaces the CMS public front.',
				'    registerCoreHomeRoute()',
				'  })',
				'  .use(features.maintenance ? middleware.maintenance() : [])',
				'',
			].join('\n'),
		},

		// ─── start/events.ts — no event-driven flows remain ─────────────────────
		{
			path: 'apps/web/start/events.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Events',
				'|--------------------------------------------------------------------------',
				'|',
				'| The `inertia` flavor has no event-driven flows: the auth and account mail',
				'| flows deliver through the mail client directly (no event bus), and the',
				'| CMS contact-form listener is pruned. This file intentionally registers',
				'| nothing; the empty export keeps it a module so the dynamic import in',
				'| adonisrc.ts typechecks under the client tsconfig.',
				'|',
				'*/',
				'',
				'export {}',
				'',
			].join('\n'),
		},

		// ─── start/nav.ts — drop the page + template nav entries ────────────────
		{
			path: 'apps/web/start/nav.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Admin navigation composition',
				'|--------------------------------------------------------------------------',
				'|',
				'| Registers the admin navigation entries of every domain existing in this',
				'| flavor of the application, in sidebar order. This file is part of the',
				"| composition set that flavor manifests may rewrite: remove a domain's",
				'| registration and its entries disappear from the admin sidebar.',
				'|',
				'*/',
				'',
				"import app from '@adonisjs/core/services/app'",
				"import { coreNavEntries, maintenanceNavEntries } from '#transport/core/nav'",
				"import { fileNavEntries } from '#transport/file/nav'",
				"import { identityNavEntries } from '#transport/identity/nav'",
				"import { loggingNavEntries } from '#transport/log/nav'",
				"import { NavRegistry } from '#core/services/nav_registry'",
				'',
				'app.container.singleton(NavRegistry, () => new NavRegistry())',
				'',
				'const registry = await app.container.make(NavRegistry)',
				'',
				"registry.register('core', coreNavEntries)",
				"registry.register('file', fileNavEntries)",
				"registry.register('identity', identityNavEntries)",
				"registry.register('maintenance', maintenanceNavEntries)",
				"registry.register('logging', loggingNavEntries)",
				'',
			].join('\n'),
		},

		// ─── start/permissions.ts — drop the page + template catalogs ───────────
		{
			path: 'apps/web/start/permissions.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| System Permission Catalog',
				'|--------------------------------------------------------------------------',
				'|',
				'| The composed list of system permission slugs for this flavor. Every',
				'| domain owns its own catalog const in its business layer (e.g.',
				'| `src/identity/permissions.ts`); this file composes those per-domain',
				'| catalogs into the single matrix the permission seeder persists.',
				"| Adding or renaming a permission only touches that domain's catalog file.",
				'|',
				'| The `permissionCatalog` object also drives the `PermissionSlug` union of',
				'| this flavor: the catalog is the single source of both the persisted slug',
				'| values and the slug type.',
				'|',
				'| The composed catalog finally yields the `permissions` identity map — one',
				'| group per category, one camelCase key per action, mapped to the raw slug',
				'| string — which route guards, nav entries and ability checks reference',
				'| instead of raw literals.',
				'|',
				'*/',
				'',
				"import { corePermissionCatalog, coreRoleSlugs, maintenancePermissionCatalog } from '#core/permissions'",
				"import { filePermissionCatalog } from '#file/permissions'",
				"import { identityPermissionCatalog } from '#identity/permissions'",
				"import { loggingPermissionCatalog } from '#log/permissions'",
				"import type { PermissionSlugs, PermissionMap } from '#types/permissions'",
				'',
				'/**',
				' * The composed system permission catalog of this flavor: `category →',
				' * actions` matrix ordered by domain (core, identity, file, maintenance,',
				' * logging). The permission seeder persists exactly this matrix, so it',
				' * is the single source of the persisted slugs.',
				' */',
				'export const permissionCatalog = {',
				'  ...corePermissionCatalog,',
				'  ...identityPermissionCatalog,',
				'  ...filePermissionCatalog,',
				'  ...maintenancePermissionCatalog,',
				'  ...loggingPermissionCatalog,',
				'}',
				'',
				'/** Union of every system permission slug in this flavor. */',
				'export type PermissionSlug = PermissionSlugs<typeof permissionCatalog>',
				'',
				'/**',
				' * The camelCase form of a snake_case permission action (`manage_roles` →',
				' * `manageRoles`); the runtime counterpart of the nested `permissions` keys.',
				' */',
				'const actionKey = (action: string): string =>',
				'  action.replace(/_([a-z])/g, (_separator, letter: string) => letter.toUpperCase())',
				'',
				'/**',
				' * Builds the nested permission identity map from a composed permission',
				' * catalog.',
				' *',
				' * The generic signature carries the {@link PermissionMap} type through the',
				" * construction, so the map's shape is derived from the catalog's type",
				' * instead of being imposed by an `as unknown as` cast at the composition.',
				' * The single cast inside the loop is confined to the runtime key iteration —',
				' * the group is typed exactly as its target and filled exhaustively, one',
				' * entry per catalog action.',
				' *',
				' * @param catalog - The composed `category → actions` permission catalog.',
				' * @returns The nested `category → camelCase action → slug` identity map.',
				' */',
				'function buildPermissionMap<Catalog extends Record<string, readonly string[]>>(',
				'  catalog: Catalog,',
				'): PermissionMap<Catalog> {',
				'  const map = {} as PermissionMap<Catalog>',
				'',
				'  for (const category of Object.keys(catalog) as Array<keyof Catalog & string>) {',
				'    const group = {} as PermissionMap<Catalog>[typeof category]',
				'',
				'    for (const action of catalog[category]) {',
				'      (group as Record<string, string>)[actionKey(action)] = `${category}.${action}`',
				'    }',
				'',
				'    map[category] = group',
				'  }',
				'',
				'  return map',
				'}',
				'',
				'/**',
				" * The nested identity map of this flavor's permission slugs: one group per",
				' * catalog category (`permissions.users`, `permissions.pages`, ...) whose',
				" * keys are the camelCase form of the category's actions",
				' * (`permissions.users.view`, `permissions.users.manageRoles`, ...) mapped to',
				' * the raw slug string. Derived at runtime from the {@link permissionCatalog},',
				' * so renaming a slug in a domain catalog file renames its key here, and',
				' * every former `permissions.*` use site fails to compile until it is updated.',
				' */',
				'export const permissions = buildPermissionMap(permissionCatalog)',
				'',
				'/**',
				' * The system role slugs of this flavor; the role seeder persists exactly',
				' * this list, so it is the single source of the persisted role slugs.',
				' */',
				'export const systemRoleSlugs = coreRoleSlugs',
				'',
				'/** Union of every system role slug in this flavor. */',
				'export type SystemRoleSlug = (typeof systemRoleSlugs)[number]',
				'',
			].join('\n'),
		},

		// ─── start/dashboard.ts — drop the page + template collectors ───────────
		{
			path: 'apps/web/start/dashboard.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Dashboard composition',
				'|--------------------------------------------------------------------------',
				'|',
				'| Registers the dashboard section collectors of every domain existing in',
				'| this flavor of the application. This file is part of the composition set',
				"| that flavor manifests may rewrite: remove a domain's registration and",
				'| its section disappears from the admin dashboard.',
				'|',
				'*/',
				'',
				"import app from '@adonisjs/core/services/app'",
				"import { FileDashboardCollector } from '#file/services/file_dashboard_collector'",
				"import { IdentityDashboardCollector } from '#identity/services/identity_dashboard_collector'",
				"import { DashboardRegistry } from '#core/services/dashboard_registry'",
				'',
				'app.container.singleton(DashboardRegistry, () => new DashboardRegistry())',
				'',
				'const registry = await app.container.make(DashboardRegistry)',
				'',
				"registry.register('identity', () => app.container.make(IdentityDashboardCollector))",
				"registry.register('file', () => app.container.make(FileDashboardCollector))",
				'',
			].join('\n'),
		},

		// ─── start/container.ts — drop the builder session binding ──────────────
		{
			path: 'apps/web/start/container.ts',
			content: [
				"import app from '@adonisjs/core/services/app'",
				"import { BackupEngine } from '#backup/services/backup_engine'",
				"import { CacheService } from '#shared/services/cache_service'",
				"import { RedisCacheDriver } from '#shared/services/cache/drivers/redis_cache_driver'",
				"import { InMemoryCacheDriver } from '#shared/services/cache/drivers/in_memory_cache_driver'",
				"import { LockService } from '#shared/services/lock_service'",
				"import { LogService } from '#log/services/log_service'",
				"import { MaintenanceService } from '#core/services/maintenance_service'",
				'',
				'/**',
				' * IoC container bindings.',
				' *',
				' * Singleton services are instantiated exactly once per process and reused',
				' * across every request — which is what makes in-flight state (locks,',
				' * sessions) work correctly without serialising to a database on every call.',
				' * Factory bindings are re-created on each resolution with runtime arguments',
				' * supplied via {@link app.container.make}.',
				' *',
				" * Add this file to `adonisrc.ts` preloads if it isn't already:",
				' *',
				' * @example',
				' * // adonisrc.ts',
				' * preloads: [',
				" *   () => import('#start/container'),",
				' * ]',
				' */',
				'',
				'// ─── BackupEngine (factory) ────────────────────────────────────────────',
				'',
				'/**',
				' * Factory binding for {@link BackupEngine} so that callers can resolve it',
				' * through the container instead of using `new`. Runtime arguments',
				' * (`strategyType`, `tempDir`) are supplied at resolution time which keeps',
				' * the strategy dynamic while still being mockable in tests via',
				' * {@link app.container.swap}.',
				' *',
				' * @example',
				" * const engine = await app.container.make(BackupEngine, ['full', 'storage/temp/backups'])",
				' */',
				'app.container.bind(BackupEngine, async (resolver, runtimeValues) => {',
				'  const [strategyType, tempDir] = runtimeValues ?? []',
				'  const logService = await resolver.make(LogService)',
				'  return new BackupEngine(strategyType, tempDir, logService)',
				'})',
				'',
				'// ─── CacheService (singleton) ──────────────────────────────────────────',
				'',
				'/**',
				' * The root `CacheService` backed by Redis.',
				' * Inject or resolve via the container anywhere in the app:',
				' *',
				' * @example',
				' * // In a service or controller',
				' * const cache = await app.container.make(CacheService)',
				' */',
				'app.container.singleton(CacheService, () => {',
				'  const driver = new RedisCacheDriver()',
				'  return new CacheService(driver)',
				'})',
				'',
				'// ─── InMemoryCacheDriver (singleton) ──────────────────────────────────────────',
				'',
				'/**',
				' * In-memory {@link CacheDriver} implementation singleton, for tests and',
				' * single-process environments. The production {@link CacheService} binding',
				' * above stays on Redis; resolve or swap this driver through the container',
				' * wherever the contract is needed.',
				' *',
				' * @example',
				' * const driver = await app.container.make(InMemoryCacheDriver)',
				" * const cache = new CacheService(driver).namespace('builder')",
				' */',
				'app.container.singleton(InMemoryCacheDriver, () => new InMemoryCacheDriver());',
				'',
				'// ─── LockService (singleton) ──────────────────────────────────────────────',
				'',
				'/**',
				' * Distributed lock service singleton.',
				' * Shared across every request and job execution so a maintenance task never',
				' * runs twice at once. Uses Redis with an in-memory fallback.',
				' *',
				' * @example',
				' * const locks = await app.container.make(LockService)',
				" * await locks.withLock('maintenance:log_prune', 1800, () => runPrune())",
				' */',
				'app.container.singleton(LockService, () => new LockService())',
				'',
				'// ─── MaintenanceService (singleton) ────────────────────────────────────',
				'',
				'/**',
				' * Maintenance service singleton.',
				' * Handles Redis + memory fallback for maintenance mode configuration.',
				' * Initializes memory fallback on first resolution.',
				' */',
				'app.container.singleton(MaintenanceService, async () => {',
				'  const service = MaintenanceService.getInstance()',
				'  await service.initializeMemoryFallback()',
				'  return service',
				'})',
				'',
			].join('\n'),
		},

		// ─── start/sitemap.ts — drop the page contributor (routes only) ─────────
		{
			path: 'apps/web/start/sitemap.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Sitemap composition',
				'|--------------------------------------------------------------------------',
				'|',
				'| Registers the sitemap contributors of every domain existing in this',
				'| flavor of the application. This file is part of the composition set',
				"| that flavor manifests may rewrite: remove a domain's registration and",
				'| its URLs disappear from `sitemap.xml`.',
				'|',
				'| The route collector is always present (hand-written `core.*.render`',
				'| routes exist in every flavor with a public front). The page collector is',
				'| CMS-specific and is removed by the `inertia` flavor manifest.',
				'|',
				'*/',
				'',
				"import app from '@adonisjs/core/services/app'",
				"import { RouteSitemapCollector } from '#core/services/route_sitemap_collector'",
				"import { SitemapRegistry } from '#core/services/sitemap_registry'",
				'',
				'app.container.singleton(SitemapRegistry, () => new SitemapRegistry())',
				'',
				'const registry = await app.container.make(SitemapRegistry)',
				'',
				"registry.register('routes', () => app.container.make(RouteSitemapCollector))",
				'',
			].join('\n'),
		},

		// ─── adonisrc.ts — drop the Transmit provider + preload ─────────────────
		{
			path: 'apps/web/adonisrc.ts',
			content: [
				"import { indexPages } from '@adonisjs/inertia'",
				"import { indexEntities } from '@adonisjs/core'",
				"import { defineConfig } from '@adonisjs/core/app'",
				"import { generateRegistry } from '@tuyau/core/hooks'",
				"import { restRoutesRegistryHook } from '#transport/core/rest/rest_routes_registry_hook'",
				'',
				'export default defineConfig({',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Experimental flags',
				'  |--------------------------------------------------------------------------',
				'  |',
				'  | The following features will be enabled by default in the next major',
				'  | release of AdonisJS. You can opt into them today to avoid any breaking',
				'  | changes during upgrade.',
				'  |',
				'  */',
				'  experimental: {},',
				'',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Commands',
				'  |--------------------------------------------------------------------------',
				'  |',
				'  | List of ace commands to register from packages. The application',
				'  | commands will be scanned automatically from the "./commands" directory.',
				'  |',
				'  */',
				'  commands: [',
				"    () => import('@adonisjs/core/commands'),",
				"    () => import('@adonisjs/lucid/commands'),",
				"    () => import('@adonisjs/session/commands'),",
				"    () => import('@adonisjs/inertia/commands'),",
				"    () => import('@adonisjs/mail/commands'),",
				"    () => import('@adonisjs/queue/commands'),",
				'  ],',
				'',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Service providers',
				'  |--------------------------------------------------------------------------',
				'  |',
				'  | List of service providers to import and register when booting the',
				'  | application',
				'  |',
				'  */',
				'  providers: [',
				"    () => import('@adonisjs/core/providers/app_provider'),",
				"    () => import('@adonisjs/core/providers/hash_provider'),",
				'    {',
				"      file: () => import('@adonisjs/core/providers/repl_provider'),",
				"      environment: ['repl', 'test'],",
				'    },',
				"    () => import('@adonisjs/core/providers/vinejs_provider'),",
				"    () => import('@adonisjs/core/providers/edge_provider'),",
				"    () => import('@adonisjs/session/session_provider'),",
				"    () => import('@adonisjs/vite/vite_provider'),",
				"    () => import('@adonisjs/shield/shield_provider'),",
				"    () => import('@adonisjs/static/static_provider'),",
				"    () => import('@adonisjs/lucid/database_provider'),",
				"    () => import('@adonisjs/cors/cors_provider'),",
				"    () => import('@adonisjs/inertia/inertia_provider'),",
				"    () => import('@adonisjs/auth/auth_provider'),",
				"    () => import('#providers/api_provider'),",
				"    () => import('@adonisjs/redis/redis_provider'),",
				"    () => import('@adonisjs/queue/queue_provider'),",
				"    () => import('#providers/sentry_provider'),",
				"    () => import('@adonisjs/i18n/i18n_provider'),",
				"    () => import('@adonisjs/ally/ally_provider'),",
				"    () => import('@adonisjs/mail/mail_provider'),",
				"    () => import('@adonisjs/drive/drive_provider'),",
				"    () => import('@adonisjs/limiter/limiter_provider'),",
				'  ],',
				'',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Preloads',
				'  |--------------------------------------------------------------------------',
				'  |',
				'  | List of modules to import before starting the application.',
				'  |',
				'  */',
				'  preloads: [',
				"    () => import('#start/routes'),",
				"    () => import('#start/kernel'),",
				"    () => import('#start/validator'),",
				"    () => import('#start/events'),",
				"    () => import('#start/container'),",
				"    () => import('#start/dashboard'),",
				"    () => import('#start/sitemap'),",
				"    () => import('#start/nav'),",
				"    () => import('#start/extensions'),",
				"    () => import('#start/scheduler'),",
				'  ],',
				'',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Tests',
				'  |--------------------------------------------------------------------------',
				'  |',
				'  | List of test suites to organize tests by their type. Feel free to',
				'  | remove and add additional suites.',
				'  |',
				'  */',
				'  tests: {',
				'    suites: [',
				'      {',
				"        files: ['tests/unit/**/*.spec.{ts,js}'],",
				"        name: 'unit',",
				'        timeout: 2000,',
				'      },',
				'      {',
				"        files: ['tests/integration/**/*.spec.{ts,js}'],",
				"        name: 'integration',",
				'        timeout: 5000,',
				'      },',
				'      {',
				"        files: ['tests/functional/**/*.spec.{ts,js}'],",
				"        name: 'functional',",
				'        timeout: 30000,',
				'      },',
				'    ],',
				'    forceExit: false,',
				'  },',
				'',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Metafiles',
				'  |--------------------------------------------------------------------------',
				'  |',
				'  | A collection of files you want to copy to the build folder when',
				'  | creating the production build.',
				'  |',
				'  */',
				'  metaFiles: [',
				'    {',
				"      pattern: 'resources/views/**/*.edge',",
				'      reloadServer: false,',
				'    },',
				'    {',
				"      pattern: 'public/**',",
				'      reloadServer: false,',
				'    },',
				'    {',
				"      pattern: 'resources/lang/**/*.{json,yaml,yml}',",
				'      reloadServer: false,',
				'    },',
				'  ],',
				'',
				'  hooks: {',
				'    init: [',
				'      indexEntities({',
				'        transformers: {',
				'          enabled: true,',
				'          withSharedProps: true,',
				"          inertiaMiddlewareImportPath: '#transport/core/middleware/inertia_middleware',",
				"          source: 'app',",
				"          importAlias: '#transport',",
				"          glob: ['**\\/*transformer.ts'],",
				'        },',
				'        controllers: {',
				'          enabled: true,',
				"          source: 'app',",
				"          importAlias: '#transport',",
				"          glob: ['**\\/*_controller.ts'],",
				'        },',
				'      }),',
				"      indexPages({ framework: 'react' }),",
				'      generateRegistry(),',
				'      restRoutesRegistryHook(),',
				'    ],',
				"    buildStarting: [() => import('@adonisjs/vite/build_hook')],",
				'  },',
				'})',
				'',
			].join('\n'),
		},

		// ─── start/env.ts — drop the CMS content-policy variables ───────────────
		{
			path: 'apps/web/start/env.ts',
			content: [
				'/*',
				'|--------------------------------------------------------------------------',
				'| Environment variables service',
				'|--------------------------------------------------------------------------',
				'|',
				'| The `Env.create` method creates an instance of the Env service. The',
				'| service validates the environment variables and also cast values',
				'| to JavaScript data types.',
				'|',
				'*/',
				'',
				"import { Env } from '@adonisjs/core/env'",
				'',
				"export default await Env.create(new URL('../', import.meta.url), {",
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring node',
				'  |----------------------------------------------------------',
				'  */',
				"  NODE_ENV: Env.schema.enum(['development', 'production', 'test'] as const),",
				'  PORT: Env.schema.number(),',
				"  HOST: Env.schema.string({ format: 'host' }),",
				'  LOG_LEVEL: Env.schema.string(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring app',
				'  |----------------------------------------------------------',
				'  */',
				'  APP_KEY: Env.schema.secret(),',
				"  APP_URL: Env.schema.string({ format: 'url', tld: false }),",
				'  APP_NAME: Env.schema.string(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring session',
				'  |----------------------------------------------------------',
				'  */',
				"  SESSION_DRIVER: Env.schema.enum(['cookie', 'memory', 'database', 'redis'] as const),",
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the auth guards',
				'  |----------------------------------------------------------',
				'  |',
				'  | Which authentication mechanisms are active. full/inertia keep the',
				'  | session guard and may opt into the token guard (REST API); the api',
				'  | flavor disables the session guard entirely.',
				'  |',
				'  */',
				'  AUTH_GUARD_WEB: Env.schema.boolean.optional(),',
				'  AUTH_GUARD_API: Env.schema.boolean.optional(),',
				'  AUTH_API_TOKEN_EXPIRY: Env.schema.string.optional(),',
				'  AUTH_API_CLIENT_URL: Env.schema.string.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring database connection',
				'  |----------------------------------------------------------',
				'  */',
				"  PG_HOST: Env.schema.string({ format: 'host' }),",
				'  PG_PORT: Env.schema.number(),',
				'  PG_USER: Env.schema.string(),',
				'  PG_PASSWORD: Env.schema.secret(),',
				'  PG_DB_NAME: Env.schema.string(),',
				'',
				'  /*',
				'  |--------------------------------------------------------------------------',
				'  | Variables for configuring @adonisjs/redis package',
				'  |--------------------------------------------------------------------------',
				'  */',
				"  REDIS_HOST: Env.schema.string({ format: 'host' }),",
				'  REDIS_PORT: Env.schema.number(),',
				'  REDIS_PASSWORD: Env.schema.string.optional(),',
				'  REDIS_SOCKET: Env.schema.string.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the queue package',
				'  |----------------------------------------------------------',
				'  */',
				"  QUEUE_DRIVER: Env.schema.enum(['redis', 'sync'] as const),",
				"  QUEUE_CONNECTION: Env.schema.enum(['main', 'local'] as const),",
				'  QUEUE_CONCURRENCY: Env.schema.number.optional(),',
				'  QUEUE_MAX_RETRIES: Env.schema.number.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring scheduled maintenance tasks',
				'  |----------------------------------------------------------',
				'  |',
				'  | Each schedule is a duration string (e.g. "1d", "24h", "30m"); "0" disables',
				'  | the task. The retention windows themselves are resolved in',
				'  | config/maintenance.ts and config/logging.ts.',
				'  |----------------------------------------------------------',
				'  */',
				'  MAINTENANCE_LOG_PRUNE_SCHEDULE: Env.schema.string.optional(),',
				'  MAINTENANCE_BACKUP_RETENTION_SCHEDULE: Env.schema.string.optional(),',
				'  LOG_RETENTION_DAYS: Env.schema.number.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the mail package',
				'  |----------------------------------------------------------',
				'  */',
				"  MAIL_MAILER: Env.schema.enum(['smtp'] as const),",
				'  MAIL_FROM_NAME: Env.schema.string(),',
				'  MAIL_FROM_ADDRESS: Env.schema.string(),',
				'  SMTP_HOST: Env.schema.string(),',
				'  SMTP_PORT: Env.schema.number(),',
				'  SMTP_USERNAME: Env.schema.string(),',
				'  SMTP_PASSWORD: Env.schema.string(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the Sentry SDK',
				'  |----------------------------------------------------------',
				'  */',
				'  SENTRY_DSN: Env.schema.string(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for Backup Configuration',
				'  |----------------------------------------------------------',
				'  */',
				"  BACKUP_STORAGE_DISK: Env.schema.enum.optional(['fs', 's3', 'r2', 'r2-backup'] as const),",
				'  BACKUP_TIME: Env.schema.string.optional(),',
				'  BACKUP_ENCRYPTION_ENABLED: Env.schema.boolean.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for Backup Configuration: Retention',
				'  |----------------------------------------------------------',
				'  */',
				'  BACKUP_RETENTION_DAILY: Env.schema.number.optional(),',
				'  BACKUP_RETENTION_WEEKLY: Env.schema.number.optional(),',
				'  BACKUP_RETENTION_MONTHLY: Env.schema.number.optional(),',
				'  BACKUP_RETENTION_YEARLY: Env.schema.number.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for Backup Configuration: Health Check',
				'  |----------------------------------------------------------',
				'  */',
				'  BACKUP_MAX_AGE_HOURS: Env.schema.number.optional(),',
				'  BACKUP_MAX_SIZE_MB: Env.schema.number.optional(),',
				'  BACKUP_MIN_FREE_SPACE_GB: Env.schema.number.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for Backup Configuration: Notifications',
				'  |----------------------------------------------------------',
				'  */',
				'  BACKUP_NOTIFICATION_EMAIL: Env.schema.string.optional(),',
				'  BACKUP_NOTIFY_SUCCESS: Env.schema.boolean.optional(),',
				'  BACKUP_NOTIFY_FAILURE: Env.schema.boolean.optional(),',
				'  BACKUP_NOTIFY_HEALTH_CHECK: Env.schema.boolean.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for Backup Configuration: Differential',
				'  |----------------------------------------------------------',
				'  */',
				'  BACKUP_EXCLUDED_TABLES: Env.schema.string.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the drive package',
				'  |----------------------------------------------------------',
				'  */',
				"  DRIVE_DISK: Env.schema.enum(['fs', 's3', 'r2'] as const),",
				'  AWS_ACCESS_KEY_ID: Env.schema.string.optional(),',
				'  AWS_SECRET_ACCESS_KEY: Env.schema.string.optional(),',
				'  AWS_REGION: Env.schema.string.optional(),',
				'  S3_BUCKET: Env.schema.string.optional(),',
				'  R2_KEY: Env.schema.string.optional(),',
				'  R2_SECRET: Env.schema.string.optional(),',
				'  R2_BUCKET: Env.schema.string.optional(),',
				'  R2_ENDPOINT: Env.schema.string.optional(),',
				'  R2_PUBLIC_URL: Env.schema.string.optional(),',
				'  /* Private R2 bucket for the backup system (no public custom domain) */',
				'  BACKUP_R2_BUCKET: Env.schema.string.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring file upload',
				'  |----------------------------------------------------------',
				'  */',
				'  MAX_UPLOAD_SIZE: Env.schema.number.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for configuring the limiter package',
				'  |----------------------------------------------------------',
				'  */',
				"  LIMITER_STORE: Env.schema.enum(['redis', 'memory'] as const),",
				'  API_RATE_LIMIT_DEFAULT: Env.schema.number.optional(),',
				'',
				'  /*',
				'  |----------------------------------------------------------',
				'  | Variables for sitemap.xml generation.',
				'  | Comma-separated lists; both have safe defaults in config/sitemap.ts.',
				'  |----------------------------------------------------------',
				'  */',
				'  SITEMAP_ADDITIONS: Env.schema.string.optional(),',
				'  SITEMAP_EXCLUSIONS: Env.schema.string.optional(),',
				'})',
				'',
			].join('\n'),
		},

		// ─── .env.example — drop the CMS content-policy variables ───────────────
		{
			path: 'apps/web/.env.example',
			content: [
				'# Node',
				'TZ=UTC',
				'PORT=3333',
				'HOST=localhost',
				'NODE_ENV=development',
				'',
				'# App',
				'LOG_LEVEL=info',
				'APP_KEY=',
				'APP_URL=http://localhost:3333',
				'APP_NAME=AdonisJS Foundry',
				'',
				'# Session',
				'SESSION_DRIVER=redis',
				'',
				'# Auth guards — which authentication mechanisms are active.',
				'# full/inertia: keep AUTH_GUARD_API unset (session only), set it to true to',
				'# also expose the token-guarded REST API (/api/v1/*) e.g. for a mobile app.',
				'# api flavor: AUTH_GUARD_WEB=false + AUTH_GUARD_API=true (no session guard).',
				'AUTH_GUARD_WEB=true',
				'AUTH_GUARD_API=false',
				'# Default lifetime of issued API tokens (e.g. "30 days", "7d", "24h").',
				'AUTH_API_TOKEN_EXPIRY=30 days',
				'# Reserved for a future OAuth API mode (redirecting non-browser clients after',
				'# a provider callback). Declared so deployments can set it, but not read yet —',
				'# mobile clients complete OAuth in a system browser, then use /api/v1/auth/login.',
				'AUTH_API_CLIENT_URL=',
				'',
				'# Database',
				'PG_HOST=127.0.0.1',
				'PG_PORT=5432',
				'PG_USER=user',
				'PG_PASSWORD=password',
				'PG_DB_NAME=app',
				'',
				'# Redis',
				'REDIS_HOST=127.0.0.1',
				'REDIS_PORT=6379',
				'REDIS_PASSWORD=',
				'REDIS_SOCKET=',
				'',
				'# Queue',
				'# redis: jobs are consumed by a separate worker (node ace queue:work).',
				'# sync: jobs run inline in the calling process (no worker, no Redis).',
				'QUEUE_DRIVER=redis',
				'# Redis connection used by the queue (see config/redis.ts).',
				'QUEUE_CONNECTION=local',
				'# Worker settings.',
				'QUEUE_CONCURRENCY=5',
				'QUEUE_MAX_RETRIES=3',
				'# Scheduled maintenance tasks (see config/maintenance.ts). Each value is a',
				'# duration string ("1d", "24h", "30m"); "0" disables the task. Unset values',
				'# fall back to a daily schedule.',
				'MAINTENANCE_LOG_PRUNE_SCHEDULE=',
				'MAINTENANCE_BACKUP_RETENTION_SCHEDULE=',
				'# Retention window in days for Log Entry pruning (default 180).',
				'LOG_RETENTION_DAYS=',
				'',
				'# Mail',
				'MAIL_MAILER=smtp',
				'MAIL_FROM_NAME=${APP_NAME}',
				'MAIL_FROM_ADDRESS=contact@example.com',
				'',
				'# SMTP',
				'SMTP_HOST=localhost',
				'SMTP_PORT=1025',
				'SMTP_USERNAME=username',
				'SMTP_PASSWORD=password',
				'',
				'# Sentry',
				'SENTRY_DSN=<your_dsn_url>',
				'',
				'# Oauth',
				'FACEBOOK_CLIENT_ID=',
				'FACEBOOK_CLIENT_SECRET=',
				'GITHUB_CLIENT_ID=',
				'GITHUB_CLIENT_SECRET=',
				'GOOGLE_CLIENT_ID=',
				'GOOGLE_CLIENT_SECRET=',
				'DRIVE_DISK=fs',
				'AWS_ACCESS_KEY_ID=',
				'AWS_SECRET_ACCESS_KEY=',
				'AWS_REGION=',
				'S3_BUCKET=',
				'R2_KEY=',
				'R2_SECRET=',
				'R2_BUCKET=',
				'R2_ENDPOINT=',
				'R2_PUBLIC_URL=',
				'# Private R2 bucket for the backup system (no public custom domain).',
				'# Used by the r2-backup disk when BACKUP_STORAGE_DISK=r2-backup.',
				'BACKUP_R2_BUCKET=',
				'LIMITER_STORE=redis',
				'# Default per-client API rate limit (requests/minute) when a user has no custom limit',
				'API_RATE_LIMIT_DEFAULT=60',
				'# Sitemap — comma-separated additions (absolute or root-relative URLs) and exclusions (route names, paths, or absolute URLs)',
				'SITEMAP_ADDITIONS=',
				'SITEMAP_EXCLUSIONS=',
				'',
			].join('\n'),
		},

		// ─── package.json (root) — monorepo scripts, typecheck without the root tsc ───
		{
			path: 'package.json',
			content: [
				'{',
				'  "name": "adonisjs-foundry",',
				'  "version": "2.1.0",',
				'  "private": true,',
				'  "license": "UNLICENSED",',
				'  "type": "module",',
				'  "workspaces": [',
				'    "apps/*",',
				'    "packages/*"',
				'  ],',
				'  "scripts": {',
				'    "start": "npm run start --workspace @foundry/web",',
				'    "dev": "npm run dev --workspace @foundry/web",',
				'    "build": "npm run build --workspace @foundry/web",',
				'    "test": "npm run test --workspace @foundry/web",',
				'    "test:front": "npm run test:front --workspace @foundry/web",',
				'    "docker:up": "docker compose up -d",',
				'    "docker:stop": "docker compose stop -d",',
				'    "lint": "oxlint",',
				'    "lint:ci": "oxlint",',
				'    "lint:fix": "oxlint --fix",',
				'    "format": "oxfmt --write .",',
				'    "format:ci": "oxfmt --check .",',
				'    "format:check": "oxfmt --check .",',
				'    "typecheck": "tsc --noEmit -p apps/web/tsconfig.json && tsc --noEmit -p apps/web/inertia/tsconfig.json && npm run typecheck --workspace @foundry/design-system",',
				'    "postinstall": "patch-package"',
				'  },',
				'  "devDependencies": {',
				'    "oxfmt": "^0.70.0",',
				'    "oxlint": "^1.85.0",',
				'    "typescript": "~5.9.3"',
				'  },',
				'  "overrides": {',
				'    "@adonisjs/ally": {',
				'      "@adonisjs/inertia": "^5.0.0"',
				'    }',
				'  },',
				'  "engines": {',
				'    "node": ">=24.0.0"',
				'  }',
				'}',
				'',
			].join('\n'),
		},

		// ─── apps/web/package.json — drop the prune alias, keep test:front ───────
		{
			path: 'apps/web/package.json',
			content: [
				'{',
				'  "name": "@foundry/web",',
				'  "version": "2.1.0",',
				'  "private": true,',
				'  "license": "UNLICENSED",',
				'  "type": "module",',
				'  "imports": {',
				'    "#transport/*": "./app/*.js",',
				'    "#generated/*": "./.adonisjs/server/*.js",',
				'    "#types/*": "./types/*.js",',
				'    "#providers/*": "./providers/*.js",',
				'    "#database/*": "./database/*.js",',
				'    "#factories/*": "./database/factories/*.js",',
				'    "#shared/*": "./src/shared/*.js",',
				'    "#core/*": "./src/core/*.js",',
				'    "#identity/*": "./src/identity/*.js",',
				'    "#auth/*": "./src/auth/*.js",',
				'    "#account/*": "./src/account/*.js",',
				'    "#file/*": "./src/file/*.js",',
				'    "#log/*": "./src/log/*.js",',
				'    "#backup/*": "./src/backup/*.js",',
				'    "#webhook/*": "./src/webhook/*.js",',
				'    "#tests/*": "./tests/*.js",',
				'    "#start/*": "./start/*.js",',
				'    "#config/*": "./config/*.js",',
				'    "#cms/*": "./src/cms/*.js"',
				'  },',
				'  "scripts": {',
				'    "start": "node bin/server.js",',
				'    "build": "node ace build",',
				'    "dev": "node ace serve --hmr",',
				'    "test": "node ace test",',
				'    "test:front": "vitest run"',
				'  },',
				'  "dependencies": {',
				'    "@adonisjs/ally": "^6.0.0",',
				'    "@adonisjs/auth": "^10.0.0",',
				'    "@adonisjs/core": "^7.0.0",',
				'    "@adonisjs/cors": "^3.0.0",',
				'    "@adonisjs/drive": "^4.0.0",',
				'    "@adonisjs/i18n": "^3.0.0",',
				'    "@adonisjs/inertia": "^5.0.0",',
				'    "@adonisjs/limiter": "^3.0.1",',
				'    "@adonisjs/lucid": "^22.0.0",',
				'    "@adonisjs/mail": "^10.0.0",',
				'    "@adonisjs/queue": "0.6.2",',
				'    "@adonisjs/redis": "^10.0.1",',
				'    "@adonisjs/session": "^8.0.0",',
				'    "@adonisjs/shield": "^9.0.0",',
				'    "@adonisjs/static": "^2.0.0",',
				'    "@adonisjs/transmit": "^3.0.2",',
				'    "@adonisjs/transmit-client": "^1.1.0",',
				'    "@adonisjs/vite": "^6.0.2",',
				'    "@aws-sdk/client-s3": "^3.1137.0",',
				'    "@aws-sdk/s3-request-presigner": "^3.1137.0",',
				'    "@fontsource/cormorant-garamond": "^5.2.11",',
				'    "@fontsource/jost": "^5.3.0",',
				'    "@fontsource/playfair-display": "^5.3.0",',
				'    "@foundry/design-system": "^2.1.0",',
				'    "@iconify/react": "^6.0.2",',
				'    "@inertiajs/react": "^3.7.1",',
				'    "@lukeed/ms": "^2.0.2",',
				'    "@scalar/api-reference": "^1.71.0",',
				'    "@sentry/node": "^10.75.2",',
				'    "@sentry/react": "^10.75.2",',
				'    "@tailwindcss/vite": "^4.2.1",',
				'    "@tuyau/core": "^1.0.0",',
				'    "@vinejs/vine": "^4.3.0",',
				'    "better-sqlite3": "^13.0.3",',
				'    "dompurify": "^3.4.16",',
				'    "edge.js": "^6.5.1",',
				'    "html-to-image": "^1.11.13",',
				'    "ipaddr.js": "^2.4.0",',
				'    "jsdom": "^30.1.1",',
				'    "luxon": "^3.7.2",',
				'    "patch-package": "^8.0.1",',
				'    "pg": "^8.22.0",',
				'    "react": "^19.3.0",',
				'    "react-dom": "^19.3.0",',
				'    "react-markdown": "^10.1.0",',
				'    "react-qr-code": "^2.2.0",',
				'    "reflect-metadata": "^0.2.2",',
				'    "rehype-raw": "^7.0.0",',
				'    "sharp": "^0.35.4",',
				'    "sinon": "^22.1.0",',
				'    "sonner": "^2.0.7",',
				'    "tailwindcss": "^4.3.3",',
				'    "uuid": "^14.0.1"',
				'  },',
				'  "devDependencies": {',
				'    "@adonisjs/assembler": "^8.5.1",',
				'    "@adonisjs/tsconfig": "^2.0.0",',
				'    "@japa/api-client": "^3.2.1",',
				'    "@japa/assert": "^4.2.0",',
				'    "@japa/plugin-adonisjs": "^5.1.0",',
				'    "@japa/runner": "^5.3.0",',
				'    "@poppinss/ts-exec": "^1.4.4",',
				'    "@seriousme/openapi-schema-validator": "^2.10.0",',
				'    "@types/dompurify": "^3.2.0",',
				'    "@types/jsdom": "^30.0.0",',
				'    "@types/luxon": "^3.7.5",',
				'    "@types/node": "~26.6.2",',
				'    "@types/react": "^19.3.0",',
				'    "@types/react-dom": "^19.3.0",',
				'    "@types/sinon": "^22.0.0",',
				'    "@vitejs/plugin-react": "^6.1.1",',
				'    "hot-hook": "^1.0.0",',
				'    "pino-pretty": "^13.1.3",',
				'    "vite": "^8.3.0",',
				'    "vitest": "^5.0.0",',
				'    "youch": "^4.1.0"',
				'  },',
				'  "engines": {',
				'    "node": ">=24.0.0"',
				'  },',
				'  "hotHook": {',
				'    "boundaries": [',
				'      "./app/**/controllers/**/*.ts",',
				'      "./app/**/middleware/**/*.ts",',
				'      "./app/**/rest/**/*.ts"',
				'    ]',
				'  }',
				'}',
				'',
			].join('\n'),
		},

		// ─── README.md — flavor-specific rewrite (conventions + upgrade path) ───
		{
			path: 'README.md',
			content: [
				'# AdonisJS Foundry — `inertia` flavor',
				'',
				'A production-ready AdonisJS v7 boilerplate with a hand-written Inertia.js + React',
				'front and a full admin back-office — without the dynamic page CMS, visual',
				'builder, or template system. This flavor is for projects that want a solid',
				'auth + admin foundation and their own hand-crafted pages.',
				'',
				'## What is included',
				'',
				'- **Admin back-office** — dashboard, users, roles, permissions, files, logs,',
				'  maintenance, settings (profile, account, preferences).',
				'- **Full auth flow** — registration, login, logout, email verification, password',
				'  reset, OAuth (GitHub, Google, Facebook), invitations, define-password.',
				'- **File management** — upload, folders, multi-disk storage (local, S3, R2),',
				'  image optimization, and server-side file resolution for hand-written pages.',
				'- **SEO** — dynamic `sitemap.xml` and `robots.txt`. Every `core.*.render`',
				'  route is collected automatically.',
				'- **Minimal front shell** — a blank home page and error pages, each served by',
				'  its own controller.',
				'',
				'Explicitly **not** included: the page domain, template domain, and the Transmit',
				'real-time integration (page builder only).',
				'',
				'## Conventions',
				'',
				'The flavor is self-documenting by construction — the files you open first are',
				'the pattern to follow:',
				'',
				'- **One controller per page.** Each public page is served by a dedicated',
				'  controller in the `core` domain (`app/core/controllers/front/`), keeping',
				'  the controller thin and delegating to services.',
				'- **`core.*.render` route names.** Public routes are declared in the core',
				'  domain entry (`app/core/routes.ts` for the home, the surface files for',
				'  the SEO endpoints) and named `core.home.render`, `core.about.render`, ...',
				'  so the sitemap collector and your frontend links reference them',
				'  consistently.',
				'- **Hand-written Inertia pages.** Front pages live under',
				'  `inertia/pages/core/front/` and use the public layout; error pages under',
				'  `inertia/pages/errors/`.',
				'- **i18n.** Each page resolves its labels from an `en`/`fr` namespace',
				'  (`resources/lang/{en,fr}/home.json`) and renders through `useTranslation`',
				'  — see `inertia/pages/core/front/home.tsx`.',
				'- **Media library in your pages.** Resolve files on the server with the',
				'  `FindFileAction` and render them with `<FileImage>` instead of hand-building',
				'  storage URLs.',
				'- **Data-driven dashboard.** The admin dashboard renders exactly the sections',
				'  present in the payload; the kept domains (users, files) register their cards',
				'  in the client-side section registry.',
				'',
				'## Quick start',
				'',
				'```bash',
				'npm install',
				'cp .env.example .env',
				'node ace generate:key',
				'node ace migration:run',
				'npm run dev',
				'```',
				'',
				'The app is available at `http://localhost:3333`. The admin is at `/admin`.',
				'',
				'## Upgrade path to `full`',
				'',
				'Choosing this flavor is not a one-way door. See',
				'`docs/flavors/inertia/upgrade-to-full.md` for the documented manual path to',
				'recover the CMS, the builder, and Transmit later.',
				'',
				'## Available scripts',
				'',
				'| Script              | Description                     |',
				'| ------------------- | ------------------------------- |',
				'| `npm run dev`       | Start the dev server with HMR   |',
				'| `npm run build`     | Build for production            |',
				'| `npm start`         | Start the production server     |',
				'| `npm test`          | Run tests (Japa)                |',
				'| `npm run lint`      | Run oxlint                      |',
				'| `npm run format`    | Format code with oxfmt          |',
				'| `npm run typecheck` | Type-check backend and frontend |',
				'',
			].join('\n'),
		},
	],

	dependencies: [
		{
			file: 'apps/web/package.json',
			packages: ['@adonisjs/transmit', '@adonisjs/transmit-client'],
		},
	],
};

export default inertiaManifest;
