/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CacheSchema extends BaseModel {
  static $columns = ['expiration', 'key', 'value'] as const
  $columns = CacheSchema.$columns
  @column()
  declare expiration: number
  @column()
  declare key: string
  @column()
  declare value: string
}

export class CacheLockSchema extends BaseModel {
  static $columns = ['expiration', 'key', 'owner'] as const
  $columns = CacheLockSchema.$columns
  @column()
  declare expiration: number
  @column()
  declare key: string
  @column()
  declare owner: string
}

export class DomainSchema extends BaseModel {
  static $columns = ['createdAt', 'domain', 'id', 'tenantId', 'updatedAt'] as const
  $columns = DomainSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare domain: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tenantId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FailedJobSchema extends BaseModel {
  static $columns = ['connection', 'exception', 'failedAt', 'id', 'payload', 'queue', 'uuid'] as const
  $columns = FailedJobSchema.$columns
  @column()
  declare connection: string
  @column()
  declare exception: string
  @column.dateTime()
  declare failedAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare payload: string
  @column()
  declare queue: string
  @column()
  declare uuid: string
}

export class FileAltSchema extends BaseModel {
  static $columns = ['createdAt', 'fileId', 'id', 'key', 'locale', 'updatedAt', 'value'] as const
  $columns = FileAltSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fileId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare locale: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class FileFolderSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'parentId', 'updatedAt'] as const
  $columns = FileFolderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare parentId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FileSchema extends BaseModel {
  static $columns = ['createdAt', 'disk', 'extension', 'filename', 'folderId', 'id', 'mimeType', 'originalName', 'path', 'size', 'updatedAt', 'uploadedBy'] as const
  $columns = FileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare disk: string
  @column()
  declare extension: string
  @column()
  declare filename: string
  @column()
  declare folderId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string
  @column()
  declare originalName: string
  @column()
  declare path: string
  @column()
  declare size: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uploadedBy: number | null
}

export class JobBatchSchema extends BaseModel {
  static $columns = ['cancelledAt', 'createdAt', 'failedJobIds', 'failedJobs', 'finishedAt', 'id', 'name', 'options', 'pendingJobs', 'totalJobs'] as const
  $columns = JobBatchSchema.$columns
  @column()
  declare cancelledAt: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare failedJobIds: string
  @column()
  declare failedJobs: number
  @column()
  declare finishedAt: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare options: string | null
  @column()
  declare pendingJobs: number
  @column()
  declare totalJobs: number
}

export class JobSchema extends BaseModel {
  static $columns = ['attempts', 'availableAt', 'createdAt', 'id', 'payload', 'queue', 'reservedAt'] as const
  $columns = JobSchema.$columns
  @column()
  declare attempts: number
  @column()
  declare availableAt: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare payload: string
  @column()
  declare queue: string
  @column()
  declare reservedAt: number | null
}

export class MigrationSchema extends BaseModel {
  static $columns = ['batch', 'id', 'migration'] as const
  $columns = MigrationSchema.$columns
  @column()
  declare batch: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare migration: string
}

export class PageRevisionSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'createdBy', 'id', 'keep', 'pageTranslationId'] as const
  $columns = PageRevisionSchema.$columns
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keep: boolean
  @column()
  declare pageTranslationId: number
}

export class PageTranslationSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'locale', 'metaDescription', 'metaTitle', 'pageId', 'publishedAt', 'slug', 'status', 'title', 'updatedAt'] as const
  $columns = PageTranslationSchema.$columns
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare metaDescription: string | null
  @column()
  declare metaTitle: string | null
  @column()
  declare pageId: number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PageSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'defaultLocale', 'id', 'isHomepage', 'metaImageId', 'updatedAt'] as const
  $columns = PageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number | null
  @column()
  declare defaultLocale: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isHomepage: boolean
  @column()
  declare metaImageId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PermissionSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'description', 'id', 'isSystem', 'name', 'slug', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'permissionId', 'roleId'] as const
  $columns = RolePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare permissionId: number
  @column()
  declare roleId: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isSystem', 'name', 'slug', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SessionSchema extends BaseModel {
  static $columns = ['id', 'ipAddress', 'lastActivity', 'payload', 'userAgent', 'userId'] as const
  $columns = SessionSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare lastActivity: number
  @column()
  declare payload: string
  @column()
  declare userAgent: string | null
  @column()
  declare userId: bigint | number | null
}

export class TemplateSchema extends BaseModel {
  static $columns = ['blockType', 'content', 'createdAt', 'createdBy', 'description', 'id', 'name', 'thumbnailId', 'type', 'updatedAt'] as const
  $columns = TemplateSchema.$columns
  @column()
  declare blockType: string | null
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare thumbnailId: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TenantSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'id', 'updatedAt'] as const
  $columns = TenantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare data: any | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TokenSchema extends BaseModel {
  static $columns = ['attempts', 'createdAt', 'expiresAt', 'id', 'selector', 'token', 'type', 'updatedAt', 'userId'] as const
  $columns = TokenSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare selector: string | null
  @column()
  declare token: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserPreferenceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'locale', 'theme', 'updatedAt', 'userId'] as const
  $columns = UserPreferenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare theme: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'emailVerifiedAt', 'facebookId', 'githubId', 'googleId', 'id', 'password', 'pendingEmail', 'roleId', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare facebookId: string | null
  @column()
  declare githubId: string | null
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare pendingEmail: string | null
  @column()
  declare roleId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
